[Migration]
Hash = "8807579493109781768"
Initial = false
Dependency = 3
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "pickupday"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 21
Column = 9

[[Migration.Operations.Fields]]
Name = "rule_date"
Type = "date"

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 28
Column = 9

[[Migration.Operations.Fields]]
Name = "pickup_date"
Type = "date"

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 32
Column = 9

[[Migration.Operations.Fields]]
Name = "deadline_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 35
Column = 9

[[Migration.Operations.Fields]]
Name = "closed"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 38
Column = 9

[[Migration.Operations.Fields]]
Name = "locked_at"
Type = "datetime"
Annotations = []

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 41
Column = 9

[[Migration.Operations.Fields]]
Name = "confirmations_sent_at"
Type = "datetime"
Annotations = []

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 47
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/pickup_day/db.rs"
Line = 54
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "shopsettings"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/settings/db.rs"
Line = 19
Column = 9

[[Migration.Operations.Fields]]
Name = "pickup_weekday"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/settings/db.rs"
Line = 22
Column = 9

[[Migration.Operations.Fields]]
Name = "deadline_offset_days"
Type = "int16"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/settings/db.rs"
Line = 25
Column = 9

[[Migration.Operations.Fields]]
Name = "deadline_time"
Type = "time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/settings/db.rs"
Line = 28
Column = 9

[[Migration.Operations.Fields]]
Name = "updated_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_update_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/semmelei/src/models/settings/db.rs"
Line = 32
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "order"

[Migration.Operations.Field]
Name = "pickup_day"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "pickupday"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/semmelei/src/models/order/db.rs"
Line = 45
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "order"

[Migration.Operations.Field]
Name = "language"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/semmelei/src/models/order/db.rs"
Line = 57
Column = 9

[[Migration.Operations]]
Type = "DeleteField"
Model = "order"
Name = "pickup_date"
