/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as ShopCheckoutRouteImport } from './routes/_shop/checkout'
import { Route as ShopCartRouteImport } from './routes/_shop/cart'
import { Route as AuthVerkaufRouteImport } from './routes/_auth/verkauf'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthVerkaufIndexRouteImport } from './routes/_auth/verkauf/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as ShopOrderPickupCodeRouteImport } from './routes/_shop/order.$pickupCode'
import { Route as AuthVerkaufPasskeysRouteImport } from './routes/_auth/verkauf/passkeys'
import { Route as AuthAdminStaffRouteImport } from './routes/_auth/admin/staff'
import { Route as AuthAdminItemsRouteImport } from './routes/_auth/admin/items'
import { Route as AuthAdminCategoriesRouteImport } from './routes/_auth/admin/categories'
import { Route as AuthVerkaufOrderOrderIdRouteImport } from './routes/_auth/verkauf/order.$orderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const AuthVerkaufRoute = AuthVerkaufRouteImport.update({
  id: '/verkauf',
  path: '/verkauf',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerkaufIndexRoute = AuthVerkaufIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthVerkaufRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const ShopOrderPickupCodeRoute = ShopOrderPickupCodeRouteImport.update({
  id: '/order/$pickupCode',
  path: '/order/$pickupCode',
  getParentRoute: () => ShopRoute,
} as any)
const AuthVerkaufPasskeysRoute = AuthVerkaufPasskeysRouteImport.update({
  id: '/passkeys',
  path: '/passkeys',
  getParentRoute: () => AuthVerkaufRoute,
} as any)
const AuthAdminStaffRoute = AuthAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminItemsRoute = AuthAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCategoriesRoute = AuthAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthVerkaufOrderOrderIdRoute = AuthVerkaufOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AuthVerkaufRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/verkauf': typeof AuthVerkaufRouteWithChildren
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/admin/categories': typeof AuthAdminCategoriesRoute
  '/admin/items': typeof AuthAdminItemsRoute
  '/admin/staff': typeof AuthAdminStaffRoute
  '/verkauf/passkeys': typeof AuthVerkaufPasskeysRoute
  '/order/$pickupCode': typeof ShopOrderPickupCodeRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/verkauf/': typeof AuthVerkaufIndexRoute
  '/verkauf/order/$orderId': typeof AuthVerkaufOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ShopIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/admin/categories': typeof AuthAdminCategoriesRoute
  '/admin/items': typeof AuthAdminItemsRoute
  '/admin/staff': typeof AuthAdminStaffRoute
  '/verkauf/passkeys': typeof AuthVerkaufPasskeysRoute
  '/order/$pickupCode': typeof ShopOrderPickupCodeRoute
  '/admin': typeof AuthAdminIndexRoute
  '/verkauf': typeof AuthVerkaufIndexRoute
  '/verkauf/order/$orderId': typeof AuthVerkaufOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_shop': typeof ShopRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/verkauf': typeof AuthVerkaufRouteWithChildren
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/': typeof ShopIndexRoute
  '/_auth/admin/categories': typeof AuthAdminCategoriesRoute
  '/_auth/admin/items': typeof AuthAdminItemsRoute
  '/_auth/admin/staff': typeof AuthAdminStaffRoute
  '/_auth/verkauf/passkeys': typeof AuthVerkaufPasskeysRoute
  '/_shop/order/$pickupCode': typeof ShopOrderPickupCodeRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/verkauf/': typeof AuthVerkaufIndexRoute
  '/_auth/verkauf/order/$orderId': typeof AuthVerkaufOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/verkauf'
    | '/cart'
    | '/checkout'
    | '/admin/categories'
    | '/admin/items'
    | '/admin/staff'
    | '/verkauf/passkeys'
    | '/order/$pickupCode'
    | '/admin/'
    | '/verkauf/'
    | '/verkauf/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/admin/categories'
    | '/admin/items'
    | '/admin/staff'
    | '/verkauf/passkeys'
    | '/order/$pickupCode'
    | '/admin'
    | '/verkauf'
    | '/verkauf/order/$orderId'
  id:
    | '__root__'
    | '/_auth'
    | '/_shop'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/verkauf'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/'
    | '/_auth/admin/categories'
    | '/_auth/admin/items'
    | '/_auth/admin/staff'
    | '/_auth/verkauf/passkeys'
    | '/_shop/order/$pickupCode'
    | '/_auth/admin/'
    | '/_auth/verkauf/'
    | '/_auth/verkauf/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_auth/verkauf': {
      id: '/_auth/verkauf'
      path: '/verkauf'
      fullPath: '/verkauf'
      preLoaderRoute: typeof AuthVerkaufRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verkauf/': {
      id: '/_auth/verkauf/'
      path: '/'
      fullPath: '/verkauf/'
      preLoaderRoute: typeof AuthVerkaufIndexRouteImport
      parentRoute: typeof AuthVerkaufRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_shop/order/$pickupCode': {
      id: '/_shop/order/$pickupCode'
      path: '/order/$pickupCode'
      fullPath: '/order/$pickupCode'
      preLoaderRoute: typeof ShopOrderPickupCodeRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_auth/verkauf/passkeys': {
      id: '/_auth/verkauf/passkeys'
      path: '/passkeys'
      fullPath: '/verkauf/passkeys'
      preLoaderRoute: typeof AuthVerkaufPasskeysRouteImport
      parentRoute: typeof AuthVerkaufRoute
    }
    '/_auth/admin/staff': {
      id: '/_auth/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthAdminStaffRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/items': {
      id: '/_auth/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AuthAdminItemsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/categories': {
      id: '/_auth/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthAdminCategoriesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/verkauf/order/$orderId': {
      id: '/_auth/verkauf/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/verkauf/order/$orderId'
      preLoaderRoute: typeof AuthVerkaufOrderOrderIdRouteImport
      parentRoute: typeof AuthVerkaufRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminCategoriesRoute: typeof AuthAdminCategoriesRoute
  AuthAdminItemsRoute: typeof AuthAdminItemsRoute
  AuthAdminStaffRoute: typeof AuthAdminStaffRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminCategoriesRoute: AuthAdminCategoriesRoute,
  AuthAdminItemsRoute: AuthAdminItemsRoute,
  AuthAdminStaffRoute: AuthAdminStaffRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthVerkaufRouteChildren {
  AuthVerkaufPasskeysRoute: typeof AuthVerkaufPasskeysRoute
  AuthVerkaufIndexRoute: typeof AuthVerkaufIndexRoute
  AuthVerkaufOrderOrderIdRoute: typeof AuthVerkaufOrderOrderIdRoute
}

const AuthVerkaufRouteChildren: AuthVerkaufRouteChildren = {
  AuthVerkaufPasskeysRoute: AuthVerkaufPasskeysRoute,
  AuthVerkaufIndexRoute: AuthVerkaufIndexRoute,
  AuthVerkaufOrderOrderIdRoute: AuthVerkaufOrderOrderIdRoute,
}

const AuthVerkaufRouteWithChildren = AuthVerkaufRoute._addFileChildren(
  AuthVerkaufRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthVerkaufRoute: typeof AuthVerkaufRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthVerkaufRoute: AuthVerkaufRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopOrderPickupCodeRoute: typeof ShopOrderPickupCodeRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopOrderPickupCodeRoute: ShopOrderPickupCodeRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
