//! Galvyn module implementing a grpc server.

use std::collections::HashSet;
use std::net::SocketAddr;
use std::sync::Mutex;

use galvyn::core::GalvynRouter;
use galvyn::core::InitError;
use galvyn::core::Module;
use galvyn::core::PostInitError;
use galvyn::core::PreInitError;
use galvyn::core::middleware::catch_unwind::CatchUnwindMiddleware;
use galvyn::core::modules::shutdown::Shutdown;
use galvyn::core::re_exports::axum;
use tokio::net::TcpListener;
use tower_http::trace::DefaultOnFailure;
use tower_http::trace::TraceLayer;
use tracing::Level;

use crate::grpc::server::GrpcService;
use crate::grpc::server::tracing::span_for_grpc_request;
use crate::nats::publisher::Nats;

/// Galvyn module implementing a grpc server.
///
/// Currently, the module itself has no public API.
///
/// See [`GrpcServerSetup`] and [module-level](super) documentation for more details.
pub struct GrpcServer {
    /// Hack to pass an argument from `init` to `post_init`
    post_init: Mutex<Option<GrpcServerPostInit>>,
}

/// The setup builder for the [`GrpcServer`] module.
///
/// It requires an address to bind on and [`GrpcService`]s.
///
/// `GrpcService` is implemented the structs generated by the `service-bootstrap-build` crate.
#[derive(Default, Debug)]
pub struct GrpcServerSetup {
    addr: Option<SocketAddr>,
    router: GalvynRouter,
    already_seen: HashSet<&'static str>,
}
impl GrpcServerSetup {
    /// Constructs a new `GrpcServerSetup` by specifying the address to bind on.
    pub fn bind_on(addr: SocketAddr) -> Self {
        Self {
            addr: Some(addr),
            router: GalvynRouter::new(),
            already_seen: HashSet::new(),
        }
    }
}
impl GrpcServerSetup {
    /// Adds a `GrpcService` to the server.
    ///
    /// This will be an instance of a struct generated by the `service-bootstrap-build` crate.
    ///
    /// ```
    /// GrpcServerSetup::bind_on("127.0.0.1:50051".parse().unwrap())
    ///     .add_service(MyServiceServer {
    ///         my_method: function_implementing_my_method,
    ///     })
    /// # ;
    /// # use std::net::SocketAddr;
    /// # use service_bootstrap::grpc::server::GrpcServerSetup;
    /// # use service_bootstrap::grpc::server::GrpcService;
    /// # use galvyn::core::GalvynRouter;
    /// #
    /// # fn function_implementing_my_method () {}
    /// #
    /// # struct MyServiceServer {
    /// #     my_method: fn() -> (),
    /// # }
    /// #
    /// # impl GrpcService for MyServiceServer {
    /// #     const FULL_NAME: &'static str = "my.package.MyService";
    /// #     fn into_router(self) -> GalvynRouter {
    /// #         GalvynRouter::new()
    /// #     }
    /// # }
    /// ```
    #[track_caller]
    pub fn add_service<T: GrpcService>(mut self, service: T) -> Self {
        if !self.already_seen.insert(T::FULL_NAME) {
            panic!("Service {} was added twice", T::FULL_NAME);
        }
        self.router = self
            .router
            .nest(&format!("/{}", T::FULL_NAME), service.into_router());
        self
    }
}

impl Module for GrpcServer {
    type Setup = GrpcServerSetup;
    type PreInit = GrpcServerPreInit;

    async fn pre_init(setup: Self::Setup) -> Result<Self::PreInit, PreInitError> {
        if setup.already_seen.is_empty() {
            return Err("Missing services for grpc server".into());
        }

        Ok(GrpcServerPreInit {
            socket: TcpListener::bind(setup.addr.ok_or("Missing address for grpc server")?).await?,
            router: setup.router,
        })
    }

    type Dependencies = (
        Nats, // To push to dlq
    );

    async fn init(
        pre_init: Self::PreInit,
        (_nats,): &mut Self::Dependencies,
    ) -> Result<Self, InitError> {
        Ok(Self {
            post_init: Mutex::new(Some(GrpcServerPostInit {
                socket: pre_init.socket,
                router: pre_init.router,
            })),
        })
    }

    async fn post_init(&'static self) -> Result<(), PostInitError> {
        let post_init = {
            let mut guard = self.post_init.lock().unwrap_or_else(|_| {
                unreachable!("Not poisoned, because this is the only lock and it is called once")
            });
            guard.take().unwrap_or_else(|| {
                unreachable!("Is some, because it was set in init and this is the only access")
            })
        };

        let (axum_router, _) = post_init
            .router
            .layer(
                TraceLayer::new_for_grpc()
                    .make_span_with(span_for_grpc_request)
                    .on_failure(DefaultOnFailure::new().level(Level::DEBUG)),
            )
            .wrap(CatchUnwindMiddleware {
                then: |_panic| tonic::Status::internal("Uncaught panic").into_http(),
            })
            .finish();

        let serve = axum::serve(post_init.socket, axum_router)
            .with_graceful_shutdown(Shutdown::global().wait_for_started());
        tokio::spawn(async move {
            let _blocker = Shutdown::global().block();
            if serve.await.is_err() {
                unreachable!("axum said, they would never error");
            }
        });

        Ok(())
    }
}

/// PreInit struct for the [`GrpcServer`] module.
#[doc(hidden)]
pub struct GrpcServerPreInit {
    socket: TcpListener,
    router: GalvynRouter,
}

/// Data passed from [`GrpcServer::init`] to [`GrpcServer::post_init`].
///
/// This is similar to `PreInit` but for `post_init`, hence the name.
#[doc(hidden)]
pub struct GrpcServerPostInit {
    socket: TcpListener,
    router: GalvynRouter,
}
