[Migration]
Hash = "15338981006488629859"
Initial = false
Dependency = 1
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "accountpasskey"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 68
Column = 9

[[Migration.Operations.Fields]]
Name = "label"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 75
Column = 9

[[Migration.Operations.Fields]]
Name = "credential_id"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 1024

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 81
Column = 9

[[Migration.Operations.Fields]]
Name = "credential"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 84
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 88
Column = 9

[[Migration.Operations.Fields]]
Name = "last_used_at"
Type = "datetime"
Annotations = []

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 91
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "registrationtoken"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 119
Column = 9

[[Migration.Operations.Fields]]
Name = "token"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 64

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 127
Column = 9

[[Migration.Operations.Fields]]
Name = "expires_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 130
Column = 9

[[Migration.Operations.Fields]]
Name = "used"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 133
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 137
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "account"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 27
Column = 9

[[Migration.Operations.Fields]]
Name = "username"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 32

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 30
Column = 9

[[Migration.Operations.Fields]]
Name = "username_normalized"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 32

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 34
Column = 9

[[Migration.Operations.Fields]]
Name = "email"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 38
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 42
Column = 9

[[Migration.Operations.Fields]]
Name = "last_login_at"
Type = "datetime"
Annotations = []

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 45
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "accountpasskey"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 72
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "registrationtoken"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/accounts/db.rs"
Line = 123
Column = 9
