[Migration]
Hash = "8211138531773520777"
Initial = false
Dependency = 8
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "deck_tag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 149
Column = 9

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 64

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 160
Column = 9

[[Migration.Operations.Fields]]
Name = "color"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 16

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 163
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 167
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "deck_card_tag"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 194
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck_tag"

[Migration.Operations.Field]
Name = "owner"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 153
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck_tag"

[Migration.Operations.Field]
Name = "deck"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "deck"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 157
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck_card_tag"

[Migration.Operations.Field]
Name = "deck_card"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "deckcard"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 202
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck_card_tag"

[Migration.Operations.Field]
Name = "tag"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "deck_tag"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 206
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck"

[Migration.Operations.Field]
Name = "share_token"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 64

[[Migration.Operations.Field.Annotations]]
Type = "unique"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 45
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck"

[Migration.Operations.Field]
Name = "allowed_color_identity"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 8

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 54
Column = 9

[[Migration.Operations]]
Type = "CreateIndex"
Model = "deckcard"

[Migration.Operations.Index]
Name = "deck_uuid"
Columns = [
    "deck",
    "uuid",
]

[[Migration.Operations]]
Type = "CreateIndex"
Model = "deck_card_tag"

[Migration.Operations.Index]
Name = "deck_card_tag"
Columns = [
    "deck_card",
    "uuid",
]

[[Migration.Operations]]
Type = "CreateIndex"
Model = "deck_card_tag"

[Migration.Operations.Index]
Columns = ["tag"]
