[Migration]
Hash = "12256337778883752224"
Initial = false
Dependency = 9
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "deck"

[Migration.Operations.Field]
Name = "bracket"
Type = "int16"
Annotations = []

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 52
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "printing"

[Migration.Operations.Field]
Name = "game_changer"
Type = "boolean"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = false

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/printing/db.rs"
Line = 159
Column = 9
