[Migration]
Hash = "11321072364089943394"
Initial = false
Dependency = 10
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "printing"

[Migration.Operations.Field]
Name = "produced_mana"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = ""

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 16

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/printing/db.rs"
Line = 160
Column = 9
