[Migration]
Hash = "10456299348395332230"
Initial = false
Dependency = 11
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "deckcard"

[Migration.Operations.Field]
Name = "foil"
Type = "boolean"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = false

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 138
Column = 9
