[Migration]
Hash = "11874518135702979491"
Initial = false
Dependency = 15
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "printing"

[Migration.Operations.Field]
Name = "image_back_small"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 512

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/printing/db.rs"
Line = 150
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "printing"

[Migration.Operations.Field]
Name = "image_back_normal"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 512

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/printing/db.rs"
Line = 153
Column = 9
