[Migration]
Hash = "325213076380492357"
Initial = false
Dependency = 24
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "catalog_sync"

[[Migration.Operations.Fields]]
Name = "id"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 32

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/catalog/db.rs"
Line = 18
Column = 9

[[Migration.Operations.Fields]]
Name = "bulk_updated_at"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 64

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/catalog/db.rs"
Line = 26
Column = 9

[[Migration.Operations.Fields]]
Name = "synced_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/catalog/db.rs"
Line = 29
Column = 9
