[Migration]
Hash = "1703738060502932618"
Initial = false
Dependency = 33
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "deck_advisor_settings"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 397
Column = 9

[[Migration.Operations.Fields]]
Name = "themes"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 407
Column = 9

[[Migration.Operations.Fields]]
Name = "targets"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 410
Column = 9

[[Migration.Operations.Fields]]
Name = "pool_query"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 512

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 413
Column = 9

[[Migration.Operations.Fields]]
Name = "ignored"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 416
Column = 9

[[Migration.Operations.Fields]]
Name = "kept"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 419
Column = 9

[[Migration.Operations.Fields]]
Name = "setup_done"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "default_value"
Value = false

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 423
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "deck_advisor_settings"

[Migration.Operations.Field]
Name = "deck"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "deck"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "unique"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/deck/db.rs"
Line = 404
Column = 9
