[Migration]
Hash = "1483164412130850607"
Initial = false
Dependency = 38
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "tournament_decklist"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 446
Column = 9

[[Migration.Operations.Fields]]
Name = "text"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 16384

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 471
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 475
Column = 9

[[Migration.Operations.Fields]]
Name = "updated_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_update_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 484
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament_decklist"

[Migration.Operations.Field]
Name = "tournament"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "tournament"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 454
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament_decklist"

[Migration.Operations.Field]
Name = "participant"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "tournament_participant"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "unique"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 460
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament_decklist"

[Migration.Operations.Field]
Name = "deck"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "deck"
ColumnName = "uuid"
OnDelete = "SetNull"
OnUpdate = "Cascade"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 468
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament"

[Migration.Operations.Field]
Name = "decklist_policy"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = "Optional"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 111
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament"

[Migration.Operations.Field]
Name = "decklists_locked_at"
Type = "datetime"
Annotations = []

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 115
Column = 9

[[Migration.Operations]]
Type = "CreateIndex"
Model = "tournament_decklist"

[Migration.Operations.Index]
Columns = ["tournament"]

[[Migration.Operations]]
Type = "CreateIndex"
Model = "tournament_decklist"

[Migration.Operations.Index]
Columns = ["deck"]
