[Migration]
Hash = "13619111993580276546"
Initial = false
Dependency = 39
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament"

[Migration.Operations.Field]
Name = "participant_audience"
Type = "varchar"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = "Participants"

[[Migration.Operations.Field.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 125
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "tournament"

[Migration.Operations.Field]
Name = "guest_names_public"
Type = "boolean"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = false

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "services/mtg/src/models/tournament/db.rs"
Line = 135
Column = 9
