/* tslint:disable */
/* eslint-disable */
/**
 * Deck Lab
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CombosRequest,
    CombosResponse,
    Diagnostics,
    DiagnosticsRequest,
    FillRequest,
    FillResult,
    HTTPValidationError,
    LineReportResponse,
    LinesRequest,
    PoolQueryRequest,
    PoolQueryResponse,
    ReplaceRequest,
    ReplaceResponse,
    SearchRequest,
    SearchResponse,
    SuggestionReport,
    SuggestionsRequest,
    SwapsRequest,
    SwapsResponse,
    WarmRequest,
} from '../models/index';

export interface PostCombosRequest {
    CombosRequest: CombosRequest;
}

export interface PostDiagnosticsRequest {
    DiagnosticsRequest: DiagnosticsRequest;
}

export interface PostFillRequest {
    FillRequest: FillRequest;
}

export interface PostLinesRequest {
    LinesRequest: LinesRequest;
}

export interface PostPoolQueryRequest {
    PoolQueryRequest: PoolQueryRequest;
}

export interface PostReplaceRequest {
    ReplaceRequest: ReplaceRequest;
}

export interface PostSearchRequest {
    SearchRequest: SearchRequest;
}

export interface PostSuggestionsRequest {
    SuggestionsRequest: SuggestionsRequest;
}

export interface PostSwapsRequest {
    SwapsRequest: SwapsRequest;
}

export interface PostWarmRequest {
    WarmRequest: WarmRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getFacets without sending the request
     */
    async getFacetsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/facets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Filter values that actually have cards behind them.
     * Get Facets
     */
    async getFacetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<{ [key: string]: any | undefined; }> | undefined; }>> {
        const requestOptions = await this.getFacetsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Filter values that actually have cards behind them.
     * Get Facets
     */
    async getFacets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<{ [key: string]: any | undefined; }> | undefined; }> {
        const response = await this.getFacetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for health without sending the request
     */
    async healthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Health
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | undefined; }>> {
        const requestOptions = await this.healthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Health
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | undefined; }> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCombos without sending the request
     */
    async postCombosRequestOpts(requestParameters: PostCombosRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['CombosRequest'] == null) {
            throw new runtime.RequiredError(
                'CombosRequest',
                'Required parameter "CombosRequest" was null or undefined when calling postCombos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/combos`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CombosRequest'],
        };
    }

    /**
     * Combos the deck completes, and combos it is one card short of.
     * Post Combos
     */
    async postCombosRaw(requestParameters: PostCombosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CombosResponse>> {
        const requestOptions = await this.postCombosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Combos the deck completes, and combos it is one card short of.
     * Post Combos
     */
    async postCombos(requestParameters: PostCombosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CombosResponse> {
        const response = await this.postCombosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postDiagnostics without sending the request
     */
    async postDiagnosticsRequestOpts(requestParameters: PostDiagnosticsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['DiagnosticsRequest'] == null) {
            throw new runtime.RequiredError(
                'DiagnosticsRequest',
                'Required parameter "DiagnosticsRequest" was null or undefined when calling postDiagnostics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/diagnostics`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['DiagnosticsRequest'],
        };
    }

    /**
     * Post Diagnostics
     */
    async postDiagnosticsRaw(requestParameters: PostDiagnosticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Diagnostics>> {
        const requestOptions = await this.postDiagnosticsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Post Diagnostics
     */
    async postDiagnostics(requestParameters: PostDiagnosticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Diagnostics> {
        const response = await this.postDiagnosticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postFill without sending the request
     */
    async postFillRequestOpts(requestParameters: PostFillRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['FillRequest'] == null) {
            throw new runtime.RequiredError(
                'FillRequest',
                'Required parameter "FillRequest" was null or undefined when calling postFill().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/fill`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['FillRequest'],
        };
    }

    /**
     * Fill an incomplete deck to `deck_size`, respecting the chosen ratios.
     * Post Fill
     */
    async postFillRaw(requestParameters: PostFillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FillResult>> {
        const requestOptions = await this.postFillRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Fill an incomplete deck to `deck_size`, respecting the chosen ratios.
     * Post Fill
     */
    async postFill(requestParameters: PostFillRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FillResult> {
        const response = await this.postFillRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postLines without sending the request
     */
    async postLinesRequestOpts(requestParameters: PostLinesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['LinesRequest'] == null) {
            throw new runtime.RequiredError(
                'LinesRequest',
                'Required parameter "LinesRequest" was null or undefined when calling postLines().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/lines`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['LinesRequest'],
        };
    }

    /**
     * Complete combo lines and near-misses: cost, colours, zones, prerequisites, fold classes, tutor reach, and redundancy.  No HTTP fallback: unlike `/combos`, the cost/zone/prerequisite data this endpoint exists for only lives on the ingested graph, so a combo layer that has never been ingested is reported as a note, not silently answered from a shape that cannot carry the fields at all.
     * Post Lines
     */
    async postLinesRaw(requestParameters: PostLinesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LineReportResponse>> {
        const requestOptions = await this.postLinesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Complete combo lines and near-misses: cost, colours, zones, prerequisites, fold classes, tutor reach, and redundancy.  No HTTP fallback: unlike `/combos`, the cost/zone/prerequisite data this endpoint exists for only lives on the ingested graph, so a combo layer that has never been ingested is reported as a note, not silently answered from a shape that cannot carry the fields at all.
     * Post Lines
     */
    async postLines(requestParameters: PostLinesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LineReportResponse> {
        const response = await this.postLinesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPoolQuery without sending the request
     */
    async postPoolQueryRequestOpts(requestParameters: PostPoolQueryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['PoolQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'PoolQueryRequest',
                'Required parameter "PoolQueryRequest" was null or undefined when calling postPoolQuery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pool-query`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['PoolQueryRequest'],
        };
    }

    /**
     * Check a pool restriction without running one.  Its own endpoint so the builder can tell someone mid-sentence that `year>=202` is not a year yet, without posting a deck or spending a suggestion. Parse-only — it never touches the graph.
     * Post Pool Query
     */
    async postPoolQueryRaw(requestParameters: PostPoolQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PoolQueryResponse>> {
        const requestOptions = await this.postPoolQueryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Check a pool restriction without running one.  Its own endpoint so the builder can tell someone mid-sentence that `year>=202` is not a year yet, without posting a deck or spending a suggestion. Parse-only — it never touches the graph.
     * Post Pool Query
     */
    async postPoolQuery(requestParameters: PostPoolQueryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PoolQueryResponse> {
        const response = await this.postPoolQueryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postReplace without sending the request
     */
    async postReplaceRequestOpts(requestParameters: PostReplaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ReplaceRequest'] == null) {
            throw new runtime.RequiredError(
                'ReplaceRequest',
                'Required parameter "ReplaceRequest" was null or undefined when calling postReplace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/replace`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['ReplaceRequest'],
        };
    }

    /**
     * Alternatives to one card the user has marked, each with its shape delta.
     * Post Replace
     */
    async postReplaceRaw(requestParameters: PostReplaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplaceResponse>> {
        const requestOptions = await this.postReplaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Alternatives to one card the user has marked, each with its shape delta.
     * Post Replace
     */
    async postReplace(requestParameters: PostReplaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplaceResponse> {
        const response = await this.postReplaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSearch without sending the request
     */
    async postSearchRequestOpts(requestParameters: PostSearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['SearchRequest'] == null) {
            throw new runtime.RequiredError(
                'SearchRequest',
                'Required parameter "SearchRequest" was null or undefined when calling postSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['SearchRequest'],
        };
    }

    /**
     * Post Search
     */
    async postSearchRaw(requestParameters: PostSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        const requestOptions = await this.postSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Post Search
     */
    async postSearch(requestParameters: PostSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.postSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSuggestions without sending the request
     */
    async postSuggestionsRequestOpts(requestParameters: PostSuggestionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['SuggestionsRequest'] == null) {
            throw new runtime.RequiredError(
                'SuggestionsRequest',
                'Required parameter "SuggestionsRequest" was null or undefined when calling postSuggestions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/suggestions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['SuggestionsRequest'],
        };
    }

    /**
     * Post Suggestions
     */
    async postSuggestionsRaw(requestParameters: PostSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuggestionReport>> {
        const requestOptions = await this.postSuggestionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Post Suggestions
     */
    async postSuggestions(requestParameters: PostSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuggestionReport> {
        const response = await this.postSuggestionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSwaps without sending the request
     */
    async postSwapsRequestOpts(requestParameters: PostSwapsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['SwapsRequest'] == null) {
            throw new runtime.RequiredError(
                'SwapsRequest',
                'Required parameter "SwapsRequest" was null or undefined when calling postSwaps().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/swaps`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['SwapsRequest'],
        };
    }

    /**
     * Post Swaps
     */
    async postSwapsRaw(requestParameters: PostSwapsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwapsResponse>> {
        const requestOptions = await this.postSwapsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Post Swaps
     */
    async postSwaps(requestParameters: PostSwapsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwapsResponse> {
        const response = await this.postSwapsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postWarm without sending the request
     */
    async postWarmRequestOpts(requestParameters: PostWarmRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['WarmRequest'] == null) {
            throw new runtime.RequiredError(
                'WarmRequest',
                'Required parameter "WarmRequest" was null or undefined when calling postWarm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/warm`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['WarmRequest'],
        };
    }

    /**
     * Prefetch EDHREC for a commander, fire-and-forget.  Called by the frontend the moment a commander is chosen, so the once-per-commander fetch happens while the deck is still being built instead of inside the first /suggestions request.
     * Post Warm
     */
    async postWarmRaw(requestParameters: PostWarmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | undefined; }>> {
        const requestOptions = await this.postWarmRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Prefetch EDHREC for a commander, fire-and-forget.  Called by the frontend the moment a commander is chosen, so the once-per-commander fetch happens while the deck is still being built instead of inside the first /suggestions request.
     * Post Warm
     */
    async postWarm(requestParameters: PostWarmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | undefined; }> {
        const response = await this.postWarmRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
