/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectRouteImport } from './routes/_collect'
import { Route as MenuRouteImport } from './routes/_menu'
import { Route as CollectListeRouteImport } from './routes/_collect/liste'
import { Route as CollectScanRouteImport } from './routes/_collect/scan'
import { Route as MenuIndexRouteImport } from './routes/_menu/index'
import { Route as MenuAuthRouteImport } from './routes/_menu/auth'
import { Route as MenuDecksRouteImport } from './routes/_menu/decks'
import { Route as MenuHomeRouteImport } from './routes/_menu/home'
import { Route as MenuWatchListsRouteImport } from './routes/_menu/watch-lists'
import { Route as CollectScanIndexRouteImport } from './routes/_collect/scan/index'
import { Route as CollectScanLiveRouteImport } from './routes/_collect/scan/live'
import { Route as MenuAuthLoginRouteImport } from './routes/_menu/auth/login'
import { Route as MenuAuthRegisterRouteImport } from './routes/_menu/auth/register'
import { Route as MenuAuthSignupRouteImport } from './routes/_menu/auth/signup'
import { Route as MenuCollectionsIndexRouteImport } from './routes/_menu/collections/index'
import { Route as MenuGlobalDecksRouteImport } from './routes/_menu/global/decks'
import { Route as MenuProfileProfileRouteImport } from './routes/_menu/profile/_profile'
import { Route as MenuCollectionsCollectionUuidCollectionRouteImport } from './routes/_menu/collections/$collectionUuid/_collection'
import { Route as MenuProfileProfileIndexRouteImport } from './routes/_menu/profile/_profile/index'
import { Route as MenuProfileProfileSecurityRouteImport } from './routes/_menu/profile/_profile/security'
import { Route as MenuProfileProfileSettingsRouteImport } from './routes/_menu/profile/_profile/settings'
import { Route as MenuCollectionsCollectionUuidCollectionIndexRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/index'
import { Route as MenuCollectionsCollectionUuidCollectionCardsRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/cards'
import { Route as MenuCollectionsCollectionUuidCollectionStatisticsRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/statistics'

const CollectRoute = CollectRouteImport.update({
  id: '/_collect',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/_menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectListeRoute = CollectListeRouteImport.update({
  id: '/liste',
  path: '/liste',
  getParentRoute: () => CollectRoute,
} as any)
const CollectScanRoute = CollectScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => CollectRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuAuthRoute = MenuAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MenuRoute,
} as any)
const MenuDecksRoute = MenuDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => MenuRoute,
} as any)
const MenuHomeRoute = MenuHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MenuRoute,
} as any)
const MenuWatchListsRoute = MenuWatchListsRouteImport.update({
  id: '/watch-lists',
  path: '/watch-lists',
  getParentRoute: () => MenuRoute,
} as any)
const CollectScanIndexRoute = CollectScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectScanRoute,
} as any)
const CollectScanLiveRoute = CollectScanLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => CollectScanRoute,
} as any)
const MenuAuthLoginRoute = MenuAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuAuthRegisterRoute = MenuAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuAuthSignupRoute = MenuAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuCollectionsIndexRoute = MenuCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuGlobalDecksRoute = MenuGlobalDecksRouteImport.update({
  id: '/global/decks',
  path: '/global/decks',
  getParentRoute: () => MenuRoute,
} as any)
const MenuProfileProfileRoute = MenuProfileProfileRouteImport.update({
  id: '/profile/_profile',
  path: '/profile',
  getParentRoute: () => MenuRoute,
} as any)
const MenuCollectionsCollectionUuidCollectionRoute =
  MenuCollectionsCollectionUuidCollectionRouteImport.update({
    id: '/collections/$collectionUuid/_collection',
    path: '/collections/$collectionUuid',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuProfileProfileIndexRoute = MenuProfileProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuProfileProfileRoute,
} as any)
const MenuProfileProfileSecurityRoute =
  MenuProfileProfileSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => MenuProfileProfileRoute,
  } as any)
const MenuProfileProfileSettingsRoute =
  MenuProfileProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MenuProfileProfileRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionIndexRoute =
  MenuCollectionsCollectionUuidCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionCardsRoute =
  MenuCollectionsCollectionUuidCollectionCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionStatisticsRoute =
  MenuCollectionsCollectionUuidCollectionStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MenuIndexRoute
  '/liste': typeof CollectListeRoute
  '/scan': typeof CollectScanRouteWithChildren
  '/auth': typeof MenuAuthRouteWithChildren
  '/decks': typeof MenuDecksRoute
  '/home': typeof MenuHomeRoute
  '/watch-lists': typeof MenuWatchListsRoute
  '/scan/live': typeof CollectScanLiveRoute
  '/auth/login': typeof MenuAuthLoginRoute
  '/auth/register': typeof MenuAuthRegisterRoute
  '/auth/signup': typeof MenuAuthSignupRoute
  '/global/decks': typeof MenuGlobalDecksRoute
  '/profile': typeof MenuProfileProfileRouteWithChildren
  '/scan/': typeof CollectScanIndexRoute
  '/collections/': typeof MenuCollectionsIndexRoute
  '/collections/$collectionUuid': typeof MenuCollectionsCollectionUuidCollectionRouteWithChildren
  '/profile/security': typeof MenuProfileProfileSecurityRoute
  '/profile/settings': typeof MenuProfileProfileSettingsRoute
  '/profile/': typeof MenuProfileProfileIndexRoute
  '/collections/$collectionUuid/cards': typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  '/collections/$collectionUuid/statistics': typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  '/collections/$collectionUuid/': typeof MenuCollectionsCollectionUuidCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MenuIndexRoute
  '/liste': typeof CollectListeRoute
  '/auth': typeof MenuAuthRouteWithChildren
  '/decks': typeof MenuDecksRoute
  '/home': typeof MenuHomeRoute
  '/watch-lists': typeof MenuWatchListsRoute
  '/scan/live': typeof CollectScanLiveRoute
  '/auth/login': typeof MenuAuthLoginRoute
  '/auth/register': typeof MenuAuthRegisterRoute
  '/auth/signup': typeof MenuAuthSignupRoute
  '/global/decks': typeof MenuGlobalDecksRoute
  '/scan': typeof CollectScanIndexRoute
  '/collections': typeof MenuCollectionsIndexRoute
  '/profile/security': typeof MenuProfileProfileSecurityRoute
  '/profile/settings': typeof MenuProfileProfileSettingsRoute
  '/profile': typeof MenuProfileProfileIndexRoute
  '/collections/$collectionUuid/cards': typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  '/collections/$collectionUuid/statistics': typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  '/collections/$collectionUuid': typeof MenuCollectionsCollectionUuidCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_collect': typeof CollectRouteWithChildren
  '/_menu': typeof MenuRouteWithChildren
  '/_collect/liste': typeof CollectListeRoute
  '/_collect/scan': typeof CollectScanRouteWithChildren
  '/_menu/auth': typeof MenuAuthRouteWithChildren
  '/_menu/decks': typeof MenuDecksRoute
  '/_menu/home': typeof MenuHomeRoute
  '/_menu/watch-lists': typeof MenuWatchListsRoute
  '/_menu/': typeof MenuIndexRoute
  '/_collect/scan/live': typeof CollectScanLiveRoute
  '/_menu/auth/login': typeof MenuAuthLoginRoute
  '/_menu/auth/register': typeof MenuAuthRegisterRoute
  '/_menu/auth/signup': typeof MenuAuthSignupRoute
  '/_menu/global/decks': typeof MenuGlobalDecksRoute
  '/_menu/profile/_profile': typeof MenuProfileProfileRouteWithChildren
  '/_collect/scan/': typeof CollectScanIndexRoute
  '/_menu/collections/': typeof MenuCollectionsIndexRoute
  '/_menu/collections/$collectionUuid/_collection': typeof MenuCollectionsCollectionUuidCollectionRouteWithChildren
  '/_menu/profile/_profile/security': typeof MenuProfileProfileSecurityRoute
  '/_menu/profile/_profile/settings': typeof MenuProfileProfileSettingsRoute
  '/_menu/profile/_profile/': typeof MenuProfileProfileIndexRoute
  '/_menu/collections/$collectionUuid/_collection/cards': typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  '/_menu/collections/$collectionUuid/_collection/statistics': typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  '/_menu/collections/$collectionUuid/_collection/': typeof MenuCollectionsCollectionUuidCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/liste'
    | '/scan'
    | '/auth'
    | '/decks'
    | '/home'
    | '/watch-lists'
    | '/scan/live'
    | '/auth/login'
    | '/auth/register'
    | '/auth/signup'
    | '/global/decks'
    | '/profile'
    | '/scan/'
    | '/collections/'
    | '/collections/$collectionUuid'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/'
    | '/collections/$collectionUuid/cards'
    | '/collections/$collectionUuid/statistics'
    | '/collections/$collectionUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/liste'
    | '/auth'
    | '/decks'
    | '/home'
    | '/watch-lists'
    | '/scan/live'
    | '/auth/login'
    | '/auth/register'
    | '/auth/signup'
    | '/global/decks'
    | '/scan'
    | '/collections'
    | '/profile/security'
    | '/profile/settings'
    | '/profile'
    | '/collections/$collectionUuid/cards'
    | '/collections/$collectionUuid/statistics'
    | '/collections/$collectionUuid'
  id:
    | '__root__'
    | '/_collect'
    | '/_menu'
    | '/_collect/liste'
    | '/_collect/scan'
    | '/_menu/auth'
    | '/_menu/decks'
    | '/_menu/home'
    | '/_menu/watch-lists'
    | '/_menu/'
    | '/_collect/scan/live'
    | '/_menu/auth/login'
    | '/_menu/auth/register'
    | '/_menu/auth/signup'
    | '/_menu/global/decks'
    | '/_menu/profile/_profile'
    | '/_collect/scan/'
    | '/_menu/collections/'
    | '/_menu/collections/$collectionUuid/_collection'
    | '/_menu/profile/_profile/security'
    | '/_menu/profile/_profile/settings'
    | '/_menu/profile/_profile/'
    | '/_menu/collections/$collectionUuid/_collection/cards'
    | '/_menu/collections/$collectionUuid/_collection/statistics'
    | '/_menu/collections/$collectionUuid/_collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CollectRoute: typeof CollectRouteWithChildren
  MenuRoute: typeof MenuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_collect': {
      id: '/_collect'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu': {
      id: '/_menu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_collect/liste': {
      id: '/_collect/liste'
      path: '/liste'
      fullPath: '/liste'
      preLoaderRoute: typeof CollectListeRouteImport
      parentRoute: typeof CollectRoute
    }
    '/_collect/scan': {
      id: '/_collect/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof CollectScanRouteImport
      parentRoute: typeof CollectRoute
    }
    '/_menu/': {
      id: '/_menu/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/auth': {
      id: '/_menu/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof MenuAuthRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/decks': {
      id: '/_menu/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof MenuDecksRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/home': {
      id: '/_menu/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MenuHomeRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/watch-lists': {
      id: '/_menu/watch-lists'
      path: '/watch-lists'
      fullPath: '/watch-lists'
      preLoaderRoute: typeof MenuWatchListsRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_collect/scan/': {
      id: '/_collect/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof CollectScanIndexRouteImport
      parentRoute: typeof CollectScanRoute
    }
    '/_collect/scan/live': {
      id: '/_collect/scan/live'
      path: '/live'
      fullPath: '/scan/live'
      preLoaderRoute: typeof CollectScanLiveRouteImport
      parentRoute: typeof CollectScanRoute
    }
    '/_menu/auth/login': {
      id: '/_menu/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof MenuAuthLoginRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/auth/register': {
      id: '/_menu/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof MenuAuthRegisterRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/auth/signup': {
      id: '/_menu/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof MenuAuthSignupRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/collections/': {
      id: '/_menu/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof MenuCollectionsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/global/decks': {
      id: '/_menu/global/decks'
      path: '/global/decks'
      fullPath: '/global/decks'
      preLoaderRoute: typeof MenuGlobalDecksRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/profile/_profile': {
      id: '/_menu/profile/_profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MenuProfileProfileRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/collections/$collectionUuid/_collection': {
      id: '/_menu/collections/$collectionUuid/_collection'
      path: '/collections/$collectionUuid'
      fullPath: '/collections/$collectionUuid'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/profile/_profile/': {
      id: '/_menu/profile/_profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MenuProfileProfileIndexRouteImport
      parentRoute: typeof MenuProfileProfileRoute
    }
    '/_menu/profile/_profile/security': {
      id: '/_menu/profile/_profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof MenuProfileProfileSecurityRouteImport
      parentRoute: typeof MenuProfileProfileRoute
    }
    '/_menu/profile/_profile/settings': {
      id: '/_menu/profile/_profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof MenuProfileProfileSettingsRouteImport
      parentRoute: typeof MenuProfileProfileRoute
    }
    '/_menu/collections/$collectionUuid/_collection/': {
      id: '/_menu/collections/$collectionUuid/_collection/'
      path: '/'
      fullPath: '/collections/$collectionUuid/'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionIndexRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/collections/$collectionUuid/_collection/cards': {
      id: '/_menu/collections/$collectionUuid/_collection/cards'
      path: '/cards'
      fullPath: '/collections/$collectionUuid/cards'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionCardsRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/collections/$collectionUuid/_collection/statistics': {
      id: '/_menu/collections/$collectionUuid/_collection/statistics'
      path: '/statistics'
      fullPath: '/collections/$collectionUuid/statistics'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionStatisticsRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
  }
}

interface CollectScanRouteChildren {
  CollectScanLiveRoute: typeof CollectScanLiveRoute
  CollectScanIndexRoute: typeof CollectScanIndexRoute
}

const CollectScanRouteChildren: CollectScanRouteChildren = {
  CollectScanLiveRoute: CollectScanLiveRoute,
  CollectScanIndexRoute: CollectScanIndexRoute,
}

const CollectScanRouteWithChildren = CollectScanRoute._addFileChildren(
  CollectScanRouteChildren,
)

interface CollectRouteChildren {
  CollectListeRoute: typeof CollectListeRoute
  CollectScanRoute: typeof CollectScanRouteWithChildren
}

const CollectRouteChildren: CollectRouteChildren = {
  CollectListeRoute: CollectListeRoute,
  CollectScanRoute: CollectScanRouteWithChildren,
}

const CollectRouteWithChildren =
  CollectRoute._addFileChildren(CollectRouteChildren)

interface MenuAuthRouteChildren {
  MenuAuthLoginRoute: typeof MenuAuthLoginRoute
  MenuAuthRegisterRoute: typeof MenuAuthRegisterRoute
  MenuAuthSignupRoute: typeof MenuAuthSignupRoute
}

const MenuAuthRouteChildren: MenuAuthRouteChildren = {
  MenuAuthLoginRoute: MenuAuthLoginRoute,
  MenuAuthRegisterRoute: MenuAuthRegisterRoute,
  MenuAuthSignupRoute: MenuAuthSignupRoute,
}

const MenuAuthRouteWithChildren = MenuAuthRoute._addFileChildren(
  MenuAuthRouteChildren,
)

interface MenuProfileProfileRouteChildren {
  MenuProfileProfileSecurityRoute: typeof MenuProfileProfileSecurityRoute
  MenuProfileProfileSettingsRoute: typeof MenuProfileProfileSettingsRoute
  MenuProfileProfileIndexRoute: typeof MenuProfileProfileIndexRoute
}

const MenuProfileProfileRouteChildren: MenuProfileProfileRouteChildren = {
  MenuProfileProfileSecurityRoute: MenuProfileProfileSecurityRoute,
  MenuProfileProfileSettingsRoute: MenuProfileProfileSettingsRoute,
  MenuProfileProfileIndexRoute: MenuProfileProfileIndexRoute,
}

const MenuProfileProfileRouteWithChildren =
  MenuProfileProfileRoute._addFileChildren(MenuProfileProfileRouteChildren)

interface MenuCollectionsCollectionUuidCollectionRouteChildren {
  MenuCollectionsCollectionUuidCollectionCardsRoute: typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  MenuCollectionsCollectionUuidCollectionStatisticsRoute: typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  MenuCollectionsCollectionUuidCollectionIndexRoute: typeof MenuCollectionsCollectionUuidCollectionIndexRoute
}

const MenuCollectionsCollectionUuidCollectionRouteChildren: MenuCollectionsCollectionUuidCollectionRouteChildren =
  {
    MenuCollectionsCollectionUuidCollectionCardsRoute:
      MenuCollectionsCollectionUuidCollectionCardsRoute,
    MenuCollectionsCollectionUuidCollectionStatisticsRoute:
      MenuCollectionsCollectionUuidCollectionStatisticsRoute,
    MenuCollectionsCollectionUuidCollectionIndexRoute:
      MenuCollectionsCollectionUuidCollectionIndexRoute,
  }

const MenuCollectionsCollectionUuidCollectionRouteWithChildren =
  MenuCollectionsCollectionUuidCollectionRoute._addFileChildren(
    MenuCollectionsCollectionUuidCollectionRouteChildren,
  )

interface MenuRouteChildren {
  MenuAuthRoute: typeof MenuAuthRouteWithChildren
  MenuDecksRoute: typeof MenuDecksRoute
  MenuHomeRoute: typeof MenuHomeRoute
  MenuWatchListsRoute: typeof MenuWatchListsRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenuGlobalDecksRoute: typeof MenuGlobalDecksRoute
  MenuProfileProfileRoute: typeof MenuProfileProfileRouteWithChildren
  MenuCollectionsIndexRoute: typeof MenuCollectionsIndexRoute
  MenuCollectionsCollectionUuidCollectionRoute: typeof MenuCollectionsCollectionUuidCollectionRouteWithChildren
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuAuthRoute: MenuAuthRouteWithChildren,
  MenuDecksRoute: MenuDecksRoute,
  MenuHomeRoute: MenuHomeRoute,
  MenuWatchListsRoute: MenuWatchListsRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenuGlobalDecksRoute: MenuGlobalDecksRoute,
  MenuProfileProfileRoute: MenuProfileProfileRouteWithChildren,
  MenuCollectionsIndexRoute: MenuCollectionsIndexRoute,
  MenuCollectionsCollectionUuidCollectionRoute:
    MenuCollectionsCollectionUuidCollectionRouteWithChildren,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CollectRoute: CollectRouteWithChildren,
  MenuRoute: MenuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
