/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListeRouteImport } from './routes/liste'
import { Route as ScanIndexRouteImport } from './routes/scan/index'
import { Route as ScanLiveRouteImport } from './routes/scan/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeRoute = ListeRouteImport.update({
  id: '/liste',
  path: '/liste',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLiveRoute = ScanLiveRouteImport.update({
  id: '/scan/live',
  path: '/scan/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liste': typeof ListeRoute
  '/scan/live': typeof ScanLiveRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liste': typeof ListeRoute
  '/scan/live': typeof ScanLiveRoute
  '/scan': typeof ScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liste': typeof ListeRoute
  '/scan/live': typeof ScanLiveRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liste' | '/scan/live' | '/scan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liste' | '/scan/live' | '/scan'
  id: '__root__' | '/' | '/liste' | '/scan/live' | '/scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListeRoute: typeof ListeRoute
  ScanLiveRoute: typeof ScanLiveRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste': {
      id: '/liste'
      path: '/liste'
      fullPath: '/liste'
      preLoaderRoute: typeof ListeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/live': {
      id: '/scan/live'
      path: '/scan/live'
      fullPath: '/scan/live'
      preLoaderRoute: typeof ScanLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListeRoute: ListeRoute,
  ScanLiveRoute: ScanLiveRoute,
  ScanIndexRoute: ScanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
