/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectRouteImport } from './routes/_collect'
import { Route as MenuRouteImport } from './routes/_menu'
import { Route as CollectListeRouteImport } from './routes/_collect/liste'
import { Route as CollectScanRouteImport } from './routes/_collect/scan'
import { Route as MenuIndexRouteImport } from './routes/_menu/index'
import { Route as MenuAuthRouteImport } from './routes/_menu/auth'
import { Route as MenuGameUtilsRouteImport } from './routes/_menu/game-utils'
import { Route as MenuHomeRouteImport } from './routes/_menu/home'
import { Route as MenuLegalRouteImport } from './routes/_menu/legal'
import { Route as MenuPrivacyRouteImport } from './routes/_menu/privacy'
import { Route as CollectScanIndexRouteImport } from './routes/_collect/scan/index'
import { Route as CollectScanLiveRouteImport } from './routes/_collect/scan/live'
import { Route as MenuAuthLoginRouteImport } from './routes/_menu/auth/login'
import { Route as MenuAuthRegisterRouteImport } from './routes/_menu/auth/register'
import { Route as MenuAuthSignupRouteImport } from './routes/_menu/auth/signup'
import { Route as MenuCollectionsIndexRouteImport } from './routes/_menu/collections/index'
import { Route as MenuDecksIndexRouteImport } from './routes/_menu/decks/index'
import { Route as MenuGameUtilsIndexRouteImport } from './routes/_menu/game-utils/index'
import { Route as MenuGameUtilsLifeTrackerRouteImport } from './routes/_menu/game-utils/life-tracker'
import { Route as MenuGameUtilsProxyPrinterRouteImport } from './routes/_menu/game-utils/proxy-printer'
import { Route as MenuProfileProfileRouteImport } from './routes/_menu/profile/_profile'
import { Route as MenuWatchListsIndexRouteImport } from './routes/_menu/watch-lists/index'
import { Route as MenuWatchListsWatchListUuidRouteImport } from './routes/_menu/watch-lists/$watchListUuid'
import { Route as MenuCollectionsCollectionUuidCollectionRouteImport } from './routes/_menu/collections/$collectionUuid/_collection'
import { Route as MenuDecksDeckUuidDeckRouteImport } from './routes/_menu/decks/$deckUuid/_deck'
import { Route as MenuGlobalDecksIndexRouteImport } from './routes/_menu/global/decks/index'
import { Route as MenuGlobalProfilesUsernameRouteImport } from './routes/_menu/global/profiles/$username'
import { Route as MenuProfileProfileIndexRouteImport } from './routes/_menu/profile/_profile/index'
import { Route as MenuProfileProfileSecurityRouteImport } from './routes/_menu/profile/_profile/security'
import { Route as MenuProfileProfileSettingsRouteImport } from './routes/_menu/profile/_profile/settings'
import { Route as MenuCollectionsCollectionUuidCollectionIndexRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/index'
import { Route as MenuCollectionsCollectionUuidCollectionCardsRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/cards'
import { Route as MenuCollectionsCollectionUuidCollectionOnLoanRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/on-loan'
import { Route as MenuCollectionsCollectionUuidCollectionStatisticsRouteImport } from './routes/_menu/collections/$collectionUuid/_collection/statistics'
import { Route as MenuDecksDeckUuidDeckIndexRouteImport } from './routes/_menu/decks/$deckUuid/_deck/index'
import { Route as MenuDecksDeckUuidDeckAdvisorRouteImport } from './routes/_menu/decks/$deckUuid/_deck/advisor'
import { Route as MenuDecksDeckUuidDeckCardsRouteImport } from './routes/_menu/decks/$deckUuid/_deck/cards'
import { Route as MenuDecksDeckUuidDeckSourcingRouteImport } from './routes/_menu/decks/$deckUuid/_deck/sourcing'
import { Route as MenuDecksDeckUuidDeckStatisticsRouteImport } from './routes/_menu/decks/$deckUuid/_deck/statistics'
import { Route as MenuGlobalCollectionsCollectionUuidCollectionRouteImport } from './routes/_menu/global/collections/$collectionUuid/_collection'
import { Route as MenuGlobalDecksDeckUuidDeckRouteImport } from './routes/_menu/global/decks/$deckUuid/_deck'
import { Route as MenuSharedCollectionsTokenSharedRouteImport } from './routes/_menu/shared/collections/$token/_shared'
import { Route as MenuSharedDecksTokenSharedRouteImport } from './routes/_menu/shared/decks/$token/_shared'
import { Route as MenuGlobalCollectionsCollectionUuidCollectionIndexRouteImport } from './routes/_menu/global/collections/$collectionUuid/_collection/index'
import { Route as MenuGlobalCollectionsCollectionUuidCollectionCardsRouteImport } from './routes/_menu/global/collections/$collectionUuid/_collection/cards'
import { Route as MenuGlobalCollectionsCollectionUuidCollectionStatisticsRouteImport } from './routes/_menu/global/collections/$collectionUuid/_collection/statistics'
import { Route as MenuGlobalDecksDeckUuidDeckIndexRouteImport } from './routes/_menu/global/decks/$deckUuid/_deck/index'
import { Route as MenuGlobalDecksDeckUuidDeckCardsRouteImport } from './routes/_menu/global/decks/$deckUuid/_deck/cards'
import { Route as MenuGlobalDecksDeckUuidDeckStatisticsRouteImport } from './routes/_menu/global/decks/$deckUuid/_deck/statistics'
import { Route as MenuSharedCollectionsTokenSharedIndexRouteImport } from './routes/_menu/shared/collections/$token/_shared/index'
import { Route as MenuSharedCollectionsTokenSharedCardsRouteImport } from './routes/_menu/shared/collections/$token/_shared/cards'
import { Route as MenuSharedCollectionsTokenSharedStatisticsRouteImport } from './routes/_menu/shared/collections/$token/_shared/statistics'
import { Route as MenuSharedDecksTokenSharedIndexRouteImport } from './routes/_menu/shared/decks/$token/_shared/index'
import { Route as MenuSharedDecksTokenSharedCardsRouteImport } from './routes/_menu/shared/decks/$token/_shared/cards'
import { Route as MenuSharedDecksTokenSharedStatisticsRouteImport } from './routes/_menu/shared/decks/$token/_shared/statistics'

const CollectRoute = CollectRouteImport.update({
  id: '/_collect',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/_menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectListeRoute = CollectListeRouteImport.update({
  id: '/liste',
  path: '/liste',
  getParentRoute: () => CollectRoute,
} as any)
const CollectScanRoute = CollectScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => CollectRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuAuthRoute = MenuAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MenuRoute,
} as any)
const MenuGameUtilsRoute = MenuGameUtilsRouteImport.update({
  id: '/game-utils',
  path: '/game-utils',
  getParentRoute: () => MenuRoute,
} as any)
const MenuHomeRoute = MenuHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MenuRoute,
} as any)
const MenuLegalRoute = MenuLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => MenuRoute,
} as any)
const MenuPrivacyRoute = MenuPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MenuRoute,
} as any)
const CollectScanIndexRoute = CollectScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectScanRoute,
} as any)
const CollectScanLiveRoute = CollectScanLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => CollectScanRoute,
} as any)
const MenuAuthLoginRoute = MenuAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuAuthRegisterRoute = MenuAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuAuthSignupRoute = MenuAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MenuAuthRoute,
} as any)
const MenuCollectionsIndexRoute = MenuCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuDecksIndexRoute = MenuDecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuGameUtilsIndexRoute = MenuGameUtilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuGameUtilsRoute,
} as any)
const MenuGameUtilsLifeTrackerRoute =
  MenuGameUtilsLifeTrackerRouteImport.update({
    id: '/life-tracker',
    path: '/life-tracker',
    getParentRoute: () => MenuGameUtilsRoute,
  } as any)
const MenuGameUtilsProxyPrinterRoute =
  MenuGameUtilsProxyPrinterRouteImport.update({
    id: '/proxy-printer',
    path: '/proxy-printer',
    getParentRoute: () => MenuGameUtilsRoute,
  } as any)
const MenuProfileProfileRoute = MenuProfileProfileRouteImport.update({
  id: '/profile/_profile',
  path: '/profile',
  getParentRoute: () => MenuRoute,
} as any)
const MenuWatchListsIndexRoute = MenuWatchListsIndexRouteImport.update({
  id: '/watch-lists/',
  path: '/watch-lists/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuWatchListsWatchListUuidRoute =
  MenuWatchListsWatchListUuidRouteImport.update({
    id: '/watch-lists/$watchListUuid',
    path: '/watch-lists/$watchListUuid',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionRoute =
  MenuCollectionsCollectionUuidCollectionRouteImport.update({
    id: '/collections/$collectionUuid/_collection',
    path: '/collections/$collectionUuid',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuDecksDeckUuidDeckRoute = MenuDecksDeckUuidDeckRouteImport.update({
  id: '/decks/$deckUuid/_deck',
  path: '/decks/$deckUuid',
  getParentRoute: () => MenuRoute,
} as any)
const MenuGlobalDecksIndexRoute = MenuGlobalDecksIndexRouteImport.update({
  id: '/global/decks/',
  path: '/global/decks/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuGlobalProfilesUsernameRoute =
  MenuGlobalProfilesUsernameRouteImport.update({
    id: '/global/profiles/$username',
    path: '/global/profiles/$username',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuProfileProfileIndexRoute = MenuProfileProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuProfileProfileRoute,
} as any)
const MenuProfileProfileSecurityRoute =
  MenuProfileProfileSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => MenuProfileProfileRoute,
  } as any)
const MenuProfileProfileSettingsRoute =
  MenuProfileProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MenuProfileProfileRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionIndexRoute =
  MenuCollectionsCollectionUuidCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionCardsRoute =
  MenuCollectionsCollectionUuidCollectionCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionOnLoanRoute =
  MenuCollectionsCollectionUuidCollectionOnLoanRouteImport.update({
    id: '/on-loan',
    path: '/on-loan',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuCollectionsCollectionUuidCollectionStatisticsRoute =
  MenuCollectionsCollectionUuidCollectionStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuDecksDeckUuidDeckIndexRoute =
  MenuDecksDeckUuidDeckIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuDecksDeckUuidDeckRoute,
  } as any)
const MenuDecksDeckUuidDeckAdvisorRoute =
  MenuDecksDeckUuidDeckAdvisorRouteImport.update({
    id: '/advisor',
    path: '/advisor',
    getParentRoute: () => MenuDecksDeckUuidDeckRoute,
  } as any)
const MenuDecksDeckUuidDeckCardsRoute =
  MenuDecksDeckUuidDeckCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuDecksDeckUuidDeckRoute,
  } as any)
const MenuDecksDeckUuidDeckSourcingRoute =
  MenuDecksDeckUuidDeckSourcingRouteImport.update({
    id: '/sourcing',
    path: '/sourcing',
    getParentRoute: () => MenuDecksDeckUuidDeckRoute,
  } as any)
const MenuDecksDeckUuidDeckStatisticsRoute =
  MenuDecksDeckUuidDeckStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuDecksDeckUuidDeckRoute,
  } as any)
const MenuGlobalCollectionsCollectionUuidCollectionRoute =
  MenuGlobalCollectionsCollectionUuidCollectionRouteImport.update({
    id: '/global/collections/$collectionUuid/_collection',
    path: '/global/collections/$collectionUuid',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuGlobalDecksDeckUuidDeckRoute =
  MenuGlobalDecksDeckUuidDeckRouteImport.update({
    id: '/global/decks/$deckUuid/_deck',
    path: '/global/decks/$deckUuid',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuSharedCollectionsTokenSharedRoute =
  MenuSharedCollectionsTokenSharedRouteImport.update({
    id: '/shared/collections/$token/_shared',
    path: '/shared/collections/$token',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuSharedDecksTokenSharedRoute =
  MenuSharedDecksTokenSharedRouteImport.update({
    id: '/shared/decks/$token/_shared',
    path: '/shared/decks/$token',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuGlobalCollectionsCollectionUuidCollectionIndexRoute =
  MenuGlobalCollectionsCollectionUuidCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuGlobalCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuGlobalCollectionsCollectionUuidCollectionCardsRoute =
  MenuGlobalCollectionsCollectionUuidCollectionCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuGlobalCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute =
  MenuGlobalCollectionsCollectionUuidCollectionStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuGlobalCollectionsCollectionUuidCollectionRoute,
  } as any)
const MenuGlobalDecksDeckUuidDeckIndexRoute =
  MenuGlobalDecksDeckUuidDeckIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuGlobalDecksDeckUuidDeckRoute,
  } as any)
const MenuGlobalDecksDeckUuidDeckCardsRoute =
  MenuGlobalDecksDeckUuidDeckCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuGlobalDecksDeckUuidDeckRoute,
  } as any)
const MenuGlobalDecksDeckUuidDeckStatisticsRoute =
  MenuGlobalDecksDeckUuidDeckStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuGlobalDecksDeckUuidDeckRoute,
  } as any)
const MenuSharedCollectionsTokenSharedIndexRoute =
  MenuSharedCollectionsTokenSharedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuSharedCollectionsTokenSharedRoute,
  } as any)
const MenuSharedCollectionsTokenSharedCardsRoute =
  MenuSharedCollectionsTokenSharedCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuSharedCollectionsTokenSharedRoute,
  } as any)
const MenuSharedCollectionsTokenSharedStatisticsRoute =
  MenuSharedCollectionsTokenSharedStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuSharedCollectionsTokenSharedRoute,
  } as any)
const MenuSharedDecksTokenSharedIndexRoute =
  MenuSharedDecksTokenSharedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MenuSharedDecksTokenSharedRoute,
  } as any)
const MenuSharedDecksTokenSharedCardsRoute =
  MenuSharedDecksTokenSharedCardsRouteImport.update({
    id: '/cards',
    path: '/cards',
    getParentRoute: () => MenuSharedDecksTokenSharedRoute,
  } as any)
const MenuSharedDecksTokenSharedStatisticsRoute =
  MenuSharedDecksTokenSharedStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MenuSharedDecksTokenSharedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MenuIndexRoute
  '/liste': typeof CollectListeRoute
  '/scan': typeof CollectScanRouteWithChildren
  '/auth': typeof MenuAuthRouteWithChildren
  '/game-utils': typeof MenuGameUtilsRouteWithChildren
  '/home': typeof MenuHomeRoute
  '/legal': typeof MenuLegalRoute
  '/privacy': typeof MenuPrivacyRoute
  '/scan/live': typeof CollectScanLiveRoute
  '/auth/login': typeof MenuAuthLoginRoute
  '/auth/register': typeof MenuAuthRegisterRoute
  '/auth/signup': typeof MenuAuthSignupRoute
  '/game-utils/life-tracker': typeof MenuGameUtilsLifeTrackerRoute
  '/game-utils/proxy-printer': typeof MenuGameUtilsProxyPrinterRoute
  '/profile': typeof MenuProfileProfileRouteWithChildren
  '/watch-lists/$watchListUuid': typeof MenuWatchListsWatchListUuidRoute
  '/scan/': typeof CollectScanIndexRoute
  '/collections/': typeof MenuCollectionsIndexRoute
  '/decks/': typeof MenuDecksIndexRoute
  '/game-utils/': typeof MenuGameUtilsIndexRoute
  '/watch-lists/': typeof MenuWatchListsIndexRoute
  '/collections/$collectionUuid': typeof MenuCollectionsCollectionUuidCollectionRouteWithChildren
  '/decks/$deckUuid': typeof MenuDecksDeckUuidDeckRouteWithChildren
  '/global/profiles/$username': typeof MenuGlobalProfilesUsernameRoute
  '/profile/security': typeof MenuProfileProfileSecurityRoute
  '/profile/settings': typeof MenuProfileProfileSettingsRoute
  '/global/decks/': typeof MenuGlobalDecksIndexRoute
  '/profile/': typeof MenuProfileProfileIndexRoute
  '/collections/$collectionUuid/cards': typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  '/collections/$collectionUuid/on-loan': typeof MenuCollectionsCollectionUuidCollectionOnLoanRoute
  '/collections/$collectionUuid/statistics': typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  '/decks/$deckUuid/advisor': typeof MenuDecksDeckUuidDeckAdvisorRoute
  '/decks/$deckUuid/cards': typeof MenuDecksDeckUuidDeckCardsRoute
  '/decks/$deckUuid/sourcing': typeof MenuDecksDeckUuidDeckSourcingRoute
  '/decks/$deckUuid/statistics': typeof MenuDecksDeckUuidDeckStatisticsRoute
  '/global/collections/$collectionUuid': typeof MenuGlobalCollectionsCollectionUuidCollectionRouteWithChildren
  '/global/decks/$deckUuid': typeof MenuGlobalDecksDeckUuidDeckRouteWithChildren
  '/shared/collections/$token': typeof MenuSharedCollectionsTokenSharedRouteWithChildren
  '/shared/decks/$token': typeof MenuSharedDecksTokenSharedRouteWithChildren
  '/collections/$collectionUuid/': typeof MenuCollectionsCollectionUuidCollectionIndexRoute
  '/decks/$deckUuid/': typeof MenuDecksDeckUuidDeckIndexRoute
  '/global/collections/$collectionUuid/cards': typeof MenuGlobalCollectionsCollectionUuidCollectionCardsRoute
  '/global/collections/$collectionUuid/statistics': typeof MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute
  '/global/decks/$deckUuid/cards': typeof MenuGlobalDecksDeckUuidDeckCardsRoute
  '/global/decks/$deckUuid/statistics': typeof MenuGlobalDecksDeckUuidDeckStatisticsRoute
  '/shared/collections/$token/cards': typeof MenuSharedCollectionsTokenSharedCardsRoute
  '/shared/collections/$token/statistics': typeof MenuSharedCollectionsTokenSharedStatisticsRoute
  '/shared/decks/$token/cards': typeof MenuSharedDecksTokenSharedCardsRoute
  '/shared/decks/$token/statistics': typeof MenuSharedDecksTokenSharedStatisticsRoute
  '/global/collections/$collectionUuid/': typeof MenuGlobalCollectionsCollectionUuidCollectionIndexRoute
  '/global/decks/$deckUuid/': typeof MenuGlobalDecksDeckUuidDeckIndexRoute
  '/shared/collections/$token/': typeof MenuSharedCollectionsTokenSharedIndexRoute
  '/shared/decks/$token/': typeof MenuSharedDecksTokenSharedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MenuIndexRoute
  '/liste': typeof CollectListeRoute
  '/auth': typeof MenuAuthRouteWithChildren
  '/home': typeof MenuHomeRoute
  '/legal': typeof MenuLegalRoute
  '/privacy': typeof MenuPrivacyRoute
  '/scan/live': typeof CollectScanLiveRoute
  '/auth/login': typeof MenuAuthLoginRoute
  '/auth/register': typeof MenuAuthRegisterRoute
  '/auth/signup': typeof MenuAuthSignupRoute
  '/game-utils/life-tracker': typeof MenuGameUtilsLifeTrackerRoute
  '/game-utils/proxy-printer': typeof MenuGameUtilsProxyPrinterRoute
  '/watch-lists/$watchListUuid': typeof MenuWatchListsWatchListUuidRoute
  '/scan': typeof CollectScanIndexRoute
  '/collections': typeof MenuCollectionsIndexRoute
  '/decks': typeof MenuDecksIndexRoute
  '/game-utils': typeof MenuGameUtilsIndexRoute
  '/watch-lists': typeof MenuWatchListsIndexRoute
  '/global/profiles/$username': typeof MenuGlobalProfilesUsernameRoute
  '/profile/security': typeof MenuProfileProfileSecurityRoute
  '/profile/settings': typeof MenuProfileProfileSettingsRoute
  '/global/decks': typeof MenuGlobalDecksIndexRoute
  '/profile': typeof MenuProfileProfileIndexRoute
  '/collections/$collectionUuid/cards': typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  '/collections/$collectionUuid/on-loan': typeof MenuCollectionsCollectionUuidCollectionOnLoanRoute
  '/collections/$collectionUuid/statistics': typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  '/decks/$deckUuid/advisor': typeof MenuDecksDeckUuidDeckAdvisorRoute
  '/decks/$deckUuid/cards': typeof MenuDecksDeckUuidDeckCardsRoute
  '/decks/$deckUuid/sourcing': typeof MenuDecksDeckUuidDeckSourcingRoute
  '/decks/$deckUuid/statistics': typeof MenuDecksDeckUuidDeckStatisticsRoute
  '/collections/$collectionUuid': typeof MenuCollectionsCollectionUuidCollectionIndexRoute
  '/decks/$deckUuid': typeof MenuDecksDeckUuidDeckIndexRoute
  '/global/collections/$collectionUuid/cards': typeof MenuGlobalCollectionsCollectionUuidCollectionCardsRoute
  '/global/collections/$collectionUuid/statistics': typeof MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute
  '/global/decks/$deckUuid/cards': typeof MenuGlobalDecksDeckUuidDeckCardsRoute
  '/global/decks/$deckUuid/statistics': typeof MenuGlobalDecksDeckUuidDeckStatisticsRoute
  '/shared/collections/$token/cards': typeof MenuSharedCollectionsTokenSharedCardsRoute
  '/shared/collections/$token/statistics': typeof MenuSharedCollectionsTokenSharedStatisticsRoute
  '/shared/decks/$token/cards': typeof MenuSharedDecksTokenSharedCardsRoute
  '/shared/decks/$token/statistics': typeof MenuSharedDecksTokenSharedStatisticsRoute
  '/global/collections/$collectionUuid': typeof MenuGlobalCollectionsCollectionUuidCollectionIndexRoute
  '/global/decks/$deckUuid': typeof MenuGlobalDecksDeckUuidDeckIndexRoute
  '/shared/collections/$token': typeof MenuSharedCollectionsTokenSharedIndexRoute
  '/shared/decks/$token': typeof MenuSharedDecksTokenSharedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_collect': typeof CollectRouteWithChildren
  '/_menu': typeof MenuRouteWithChildren
  '/_collect/liste': typeof CollectListeRoute
  '/_collect/scan': typeof CollectScanRouteWithChildren
  '/_menu/auth': typeof MenuAuthRouteWithChildren
  '/_menu/game-utils': typeof MenuGameUtilsRouteWithChildren
  '/_menu/home': typeof MenuHomeRoute
  '/_menu/legal': typeof MenuLegalRoute
  '/_menu/privacy': typeof MenuPrivacyRoute
  '/_menu/': typeof MenuIndexRoute
  '/_collect/scan/live': typeof CollectScanLiveRoute
  '/_menu/auth/login': typeof MenuAuthLoginRoute
  '/_menu/auth/register': typeof MenuAuthRegisterRoute
  '/_menu/auth/signup': typeof MenuAuthSignupRoute
  '/_menu/game-utils/life-tracker': typeof MenuGameUtilsLifeTrackerRoute
  '/_menu/game-utils/proxy-printer': typeof MenuGameUtilsProxyPrinterRoute
  '/_menu/profile/_profile': typeof MenuProfileProfileRouteWithChildren
  '/_menu/watch-lists/$watchListUuid': typeof MenuWatchListsWatchListUuidRoute
  '/_collect/scan/': typeof CollectScanIndexRoute
  '/_menu/collections/': typeof MenuCollectionsIndexRoute
  '/_menu/decks/': typeof MenuDecksIndexRoute
  '/_menu/game-utils/': typeof MenuGameUtilsIndexRoute
  '/_menu/watch-lists/': typeof MenuWatchListsIndexRoute
  '/_menu/collections/$collectionUuid/_collection': typeof MenuCollectionsCollectionUuidCollectionRouteWithChildren
  '/_menu/decks/$deckUuid/_deck': typeof MenuDecksDeckUuidDeckRouteWithChildren
  '/_menu/global/profiles/$username': typeof MenuGlobalProfilesUsernameRoute
  '/_menu/profile/_profile/security': typeof MenuProfileProfileSecurityRoute
  '/_menu/profile/_profile/settings': typeof MenuProfileProfileSettingsRoute
  '/_menu/global/decks/': typeof MenuGlobalDecksIndexRoute
  '/_menu/profile/_profile/': typeof MenuProfileProfileIndexRoute
  '/_menu/collections/$collectionUuid/_collection/cards': typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  '/_menu/collections/$collectionUuid/_collection/on-loan': typeof MenuCollectionsCollectionUuidCollectionOnLoanRoute
  '/_menu/collections/$collectionUuid/_collection/statistics': typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  '/_menu/decks/$deckUuid/_deck/advisor': typeof MenuDecksDeckUuidDeckAdvisorRoute
  '/_menu/decks/$deckUuid/_deck/cards': typeof MenuDecksDeckUuidDeckCardsRoute
  '/_menu/decks/$deckUuid/_deck/sourcing': typeof MenuDecksDeckUuidDeckSourcingRoute
  '/_menu/decks/$deckUuid/_deck/statistics': typeof MenuDecksDeckUuidDeckStatisticsRoute
  '/_menu/global/collections/$collectionUuid/_collection': typeof MenuGlobalCollectionsCollectionUuidCollectionRouteWithChildren
  '/_menu/global/decks/$deckUuid/_deck': typeof MenuGlobalDecksDeckUuidDeckRouteWithChildren
  '/_menu/shared/collections/$token/_shared': typeof MenuSharedCollectionsTokenSharedRouteWithChildren
  '/_menu/shared/decks/$token/_shared': typeof MenuSharedDecksTokenSharedRouteWithChildren
  '/_menu/collections/$collectionUuid/_collection/': typeof MenuCollectionsCollectionUuidCollectionIndexRoute
  '/_menu/decks/$deckUuid/_deck/': typeof MenuDecksDeckUuidDeckIndexRoute
  '/_menu/global/collections/$collectionUuid/_collection/cards': typeof MenuGlobalCollectionsCollectionUuidCollectionCardsRoute
  '/_menu/global/collections/$collectionUuid/_collection/statistics': typeof MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute
  '/_menu/global/decks/$deckUuid/_deck/cards': typeof MenuGlobalDecksDeckUuidDeckCardsRoute
  '/_menu/global/decks/$deckUuid/_deck/statistics': typeof MenuGlobalDecksDeckUuidDeckStatisticsRoute
  '/_menu/shared/collections/$token/_shared/cards': typeof MenuSharedCollectionsTokenSharedCardsRoute
  '/_menu/shared/collections/$token/_shared/statistics': typeof MenuSharedCollectionsTokenSharedStatisticsRoute
  '/_menu/shared/decks/$token/_shared/cards': typeof MenuSharedDecksTokenSharedCardsRoute
  '/_menu/shared/decks/$token/_shared/statistics': typeof MenuSharedDecksTokenSharedStatisticsRoute
  '/_menu/global/collections/$collectionUuid/_collection/': typeof MenuGlobalCollectionsCollectionUuidCollectionIndexRoute
  '/_menu/global/decks/$deckUuid/_deck/': typeof MenuGlobalDecksDeckUuidDeckIndexRoute
  '/_menu/shared/collections/$token/_shared/': typeof MenuSharedCollectionsTokenSharedIndexRoute
  '/_menu/shared/decks/$token/_shared/': typeof MenuSharedDecksTokenSharedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/liste'
    | '/scan'
    | '/auth'
    | '/game-utils'
    | '/home'
    | '/legal'
    | '/privacy'
    | '/scan/live'
    | '/auth/login'
    | '/auth/register'
    | '/auth/signup'
    | '/game-utils/life-tracker'
    | '/game-utils/proxy-printer'
    | '/profile'
    | '/watch-lists/$watchListUuid'
    | '/scan/'
    | '/collections/'
    | '/decks/'
    | '/game-utils/'
    | '/watch-lists/'
    | '/collections/$collectionUuid'
    | '/decks/$deckUuid'
    | '/global/profiles/$username'
    | '/profile/security'
    | '/profile/settings'
    | '/global/decks/'
    | '/profile/'
    | '/collections/$collectionUuid/cards'
    | '/collections/$collectionUuid/on-loan'
    | '/collections/$collectionUuid/statistics'
    | '/decks/$deckUuid/advisor'
    | '/decks/$deckUuid/cards'
    | '/decks/$deckUuid/sourcing'
    | '/decks/$deckUuid/statistics'
    | '/global/collections/$collectionUuid'
    | '/global/decks/$deckUuid'
    | '/shared/collections/$token'
    | '/shared/decks/$token'
    | '/collections/$collectionUuid/'
    | '/decks/$deckUuid/'
    | '/global/collections/$collectionUuid/cards'
    | '/global/collections/$collectionUuid/statistics'
    | '/global/decks/$deckUuid/cards'
    | '/global/decks/$deckUuid/statistics'
    | '/shared/collections/$token/cards'
    | '/shared/collections/$token/statistics'
    | '/shared/decks/$token/cards'
    | '/shared/decks/$token/statistics'
    | '/global/collections/$collectionUuid/'
    | '/global/decks/$deckUuid/'
    | '/shared/collections/$token/'
    | '/shared/decks/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/liste'
    | '/auth'
    | '/home'
    | '/legal'
    | '/privacy'
    | '/scan/live'
    | '/auth/login'
    | '/auth/register'
    | '/auth/signup'
    | '/game-utils/life-tracker'
    | '/game-utils/proxy-printer'
    | '/watch-lists/$watchListUuid'
    | '/scan'
    | '/collections'
    | '/decks'
    | '/game-utils'
    | '/watch-lists'
    | '/global/profiles/$username'
    | '/profile/security'
    | '/profile/settings'
    | '/global/decks'
    | '/profile'
    | '/collections/$collectionUuid/cards'
    | '/collections/$collectionUuid/on-loan'
    | '/collections/$collectionUuid/statistics'
    | '/decks/$deckUuid/advisor'
    | '/decks/$deckUuid/cards'
    | '/decks/$deckUuid/sourcing'
    | '/decks/$deckUuid/statistics'
    | '/collections/$collectionUuid'
    | '/decks/$deckUuid'
    | '/global/collections/$collectionUuid/cards'
    | '/global/collections/$collectionUuid/statistics'
    | '/global/decks/$deckUuid/cards'
    | '/global/decks/$deckUuid/statistics'
    | '/shared/collections/$token/cards'
    | '/shared/collections/$token/statistics'
    | '/shared/decks/$token/cards'
    | '/shared/decks/$token/statistics'
    | '/global/collections/$collectionUuid'
    | '/global/decks/$deckUuid'
    | '/shared/collections/$token'
    | '/shared/decks/$token'
  id:
    | '__root__'
    | '/_collect'
    | '/_menu'
    | '/_collect/liste'
    | '/_collect/scan'
    | '/_menu/auth'
    | '/_menu/game-utils'
    | '/_menu/home'
    | '/_menu/legal'
    | '/_menu/privacy'
    | '/_menu/'
    | '/_collect/scan/live'
    | '/_menu/auth/login'
    | '/_menu/auth/register'
    | '/_menu/auth/signup'
    | '/_menu/game-utils/life-tracker'
    | '/_menu/game-utils/proxy-printer'
    | '/_menu/profile/_profile'
    | '/_menu/watch-lists/$watchListUuid'
    | '/_collect/scan/'
    | '/_menu/collections/'
    | '/_menu/decks/'
    | '/_menu/game-utils/'
    | '/_menu/watch-lists/'
    | '/_menu/collections/$collectionUuid/_collection'
    | '/_menu/decks/$deckUuid/_deck'
    | '/_menu/global/profiles/$username'
    | '/_menu/profile/_profile/security'
    | '/_menu/profile/_profile/settings'
    | '/_menu/global/decks/'
    | '/_menu/profile/_profile/'
    | '/_menu/collections/$collectionUuid/_collection/cards'
    | '/_menu/collections/$collectionUuid/_collection/on-loan'
    | '/_menu/collections/$collectionUuid/_collection/statistics'
    | '/_menu/decks/$deckUuid/_deck/advisor'
    | '/_menu/decks/$deckUuid/_deck/cards'
    | '/_menu/decks/$deckUuid/_deck/sourcing'
    | '/_menu/decks/$deckUuid/_deck/statistics'
    | '/_menu/global/collections/$collectionUuid/_collection'
    | '/_menu/global/decks/$deckUuid/_deck'
    | '/_menu/shared/collections/$token/_shared'
    | '/_menu/shared/decks/$token/_shared'
    | '/_menu/collections/$collectionUuid/_collection/'
    | '/_menu/decks/$deckUuid/_deck/'
    | '/_menu/global/collections/$collectionUuid/_collection/cards'
    | '/_menu/global/collections/$collectionUuid/_collection/statistics'
    | '/_menu/global/decks/$deckUuid/_deck/cards'
    | '/_menu/global/decks/$deckUuid/_deck/statistics'
    | '/_menu/shared/collections/$token/_shared/cards'
    | '/_menu/shared/collections/$token/_shared/statistics'
    | '/_menu/shared/decks/$token/_shared/cards'
    | '/_menu/shared/decks/$token/_shared/statistics'
    | '/_menu/global/collections/$collectionUuid/_collection/'
    | '/_menu/global/decks/$deckUuid/_deck/'
    | '/_menu/shared/collections/$token/_shared/'
    | '/_menu/shared/decks/$token/_shared/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CollectRoute: typeof CollectRouteWithChildren
  MenuRoute: typeof MenuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_collect': {
      id: '/_collect'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu': {
      id: '/_menu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_collect/liste': {
      id: '/_collect/liste'
      path: '/liste'
      fullPath: '/liste'
      preLoaderRoute: typeof CollectListeRouteImport
      parentRoute: typeof CollectRoute
    }
    '/_collect/scan': {
      id: '/_collect/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof CollectScanRouteImport
      parentRoute: typeof CollectRoute
    }
    '/_menu/': {
      id: '/_menu/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/auth': {
      id: '/_menu/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof MenuAuthRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/game-utils': {
      id: '/_menu/game-utils'
      path: '/game-utils'
      fullPath: '/game-utils'
      preLoaderRoute: typeof MenuGameUtilsRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/home': {
      id: '/_menu/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MenuHomeRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/legal': {
      id: '/_menu/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof MenuLegalRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/privacy': {
      id: '/_menu/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MenuPrivacyRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_collect/scan/': {
      id: '/_collect/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof CollectScanIndexRouteImport
      parentRoute: typeof CollectScanRoute
    }
    '/_collect/scan/live': {
      id: '/_collect/scan/live'
      path: '/live'
      fullPath: '/scan/live'
      preLoaderRoute: typeof CollectScanLiveRouteImport
      parentRoute: typeof CollectScanRoute
    }
    '/_menu/auth/login': {
      id: '/_menu/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof MenuAuthLoginRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/auth/register': {
      id: '/_menu/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof MenuAuthRegisterRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/auth/signup': {
      id: '/_menu/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof MenuAuthSignupRouteImport
      parentRoute: typeof MenuAuthRoute
    }
    '/_menu/collections/': {
      id: '/_menu/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof MenuCollectionsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/decks/': {
      id: '/_menu/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof MenuDecksIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/game-utils/': {
      id: '/_menu/game-utils/'
      path: '/'
      fullPath: '/game-utils/'
      preLoaderRoute: typeof MenuGameUtilsIndexRouteImport
      parentRoute: typeof MenuGameUtilsRoute
    }
    '/_menu/game-utils/life-tracker': {
      id: '/_menu/game-utils/life-tracker'
      path: '/life-tracker'
      fullPath: '/game-utils/life-tracker'
      preLoaderRoute: typeof MenuGameUtilsLifeTrackerRouteImport
      parentRoute: typeof MenuGameUtilsRoute
    }
    '/_menu/game-utils/proxy-printer': {
      id: '/_menu/game-utils/proxy-printer'
      path: '/proxy-printer'
      fullPath: '/game-utils/proxy-printer'
      preLoaderRoute: typeof MenuGameUtilsProxyPrinterRouteImport
      parentRoute: typeof MenuGameUtilsRoute
    }
    '/_menu/profile/_profile': {
      id: '/_menu/profile/_profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MenuProfileProfileRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/watch-lists/': {
      id: '/_menu/watch-lists/'
      path: '/watch-lists'
      fullPath: '/watch-lists/'
      preLoaderRoute: typeof MenuWatchListsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/watch-lists/$watchListUuid': {
      id: '/_menu/watch-lists/$watchListUuid'
      path: '/watch-lists/$watchListUuid'
      fullPath: '/watch-lists/$watchListUuid'
      preLoaderRoute: typeof MenuWatchListsWatchListUuidRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/collections/$collectionUuid/_collection': {
      id: '/_menu/collections/$collectionUuid/_collection'
      path: '/collections/$collectionUuid'
      fullPath: '/collections/$collectionUuid'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/decks/$deckUuid/_deck': {
      id: '/_menu/decks/$deckUuid/_deck'
      path: '/decks/$deckUuid'
      fullPath: '/decks/$deckUuid'
      preLoaderRoute: typeof MenuDecksDeckUuidDeckRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/global/decks/': {
      id: '/_menu/global/decks/'
      path: '/global/decks'
      fullPath: '/global/decks/'
      preLoaderRoute: typeof MenuGlobalDecksIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/global/profiles/$username': {
      id: '/_menu/global/profiles/$username'
      path: '/global/profiles/$username'
      fullPath: '/global/profiles/$username'
      preLoaderRoute: typeof MenuGlobalProfilesUsernameRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/profile/_profile/': {
      id: '/_menu/profile/_profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MenuProfileProfileIndexRouteImport
      parentRoute: typeof MenuProfileProfileRoute
    }
    '/_menu/profile/_profile/security': {
      id: '/_menu/profile/_profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof MenuProfileProfileSecurityRouteImport
      parentRoute: typeof MenuProfileProfileRoute
    }
    '/_menu/profile/_profile/settings': {
      id: '/_menu/profile/_profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof MenuProfileProfileSettingsRouteImport
      parentRoute: typeof MenuProfileProfileRoute
    }
    '/_menu/collections/$collectionUuid/_collection/': {
      id: '/_menu/collections/$collectionUuid/_collection/'
      path: '/'
      fullPath: '/collections/$collectionUuid/'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionIndexRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/collections/$collectionUuid/_collection/cards': {
      id: '/_menu/collections/$collectionUuid/_collection/cards'
      path: '/cards'
      fullPath: '/collections/$collectionUuid/cards'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionCardsRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/collections/$collectionUuid/_collection/on-loan': {
      id: '/_menu/collections/$collectionUuid/_collection/on-loan'
      path: '/on-loan'
      fullPath: '/collections/$collectionUuid/on-loan'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionOnLoanRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/collections/$collectionUuid/_collection/statistics': {
      id: '/_menu/collections/$collectionUuid/_collection/statistics'
      path: '/statistics'
      fullPath: '/collections/$collectionUuid/statistics'
      preLoaderRoute: typeof MenuCollectionsCollectionUuidCollectionStatisticsRouteImport
      parentRoute: typeof MenuCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/decks/$deckUuid/_deck/': {
      id: '/_menu/decks/$deckUuid/_deck/'
      path: '/'
      fullPath: '/decks/$deckUuid/'
      preLoaderRoute: typeof MenuDecksDeckUuidDeckIndexRouteImport
      parentRoute: typeof MenuDecksDeckUuidDeckRoute
    }
    '/_menu/decks/$deckUuid/_deck/advisor': {
      id: '/_menu/decks/$deckUuid/_deck/advisor'
      path: '/advisor'
      fullPath: '/decks/$deckUuid/advisor'
      preLoaderRoute: typeof MenuDecksDeckUuidDeckAdvisorRouteImport
      parentRoute: typeof MenuDecksDeckUuidDeckRoute
    }
    '/_menu/decks/$deckUuid/_deck/cards': {
      id: '/_menu/decks/$deckUuid/_deck/cards'
      path: '/cards'
      fullPath: '/decks/$deckUuid/cards'
      preLoaderRoute: typeof MenuDecksDeckUuidDeckCardsRouteImport
      parentRoute: typeof MenuDecksDeckUuidDeckRoute
    }
    '/_menu/decks/$deckUuid/_deck/sourcing': {
      id: '/_menu/decks/$deckUuid/_deck/sourcing'
      path: '/sourcing'
      fullPath: '/decks/$deckUuid/sourcing'
      preLoaderRoute: typeof MenuDecksDeckUuidDeckSourcingRouteImport
      parentRoute: typeof MenuDecksDeckUuidDeckRoute
    }
    '/_menu/decks/$deckUuid/_deck/statistics': {
      id: '/_menu/decks/$deckUuid/_deck/statistics'
      path: '/statistics'
      fullPath: '/decks/$deckUuid/statistics'
      preLoaderRoute: typeof MenuDecksDeckUuidDeckStatisticsRouteImport
      parentRoute: typeof MenuDecksDeckUuidDeckRoute
    }
    '/_menu/global/collections/$collectionUuid/_collection': {
      id: '/_menu/global/collections/$collectionUuid/_collection'
      path: '/global/collections/$collectionUuid'
      fullPath: '/global/collections/$collectionUuid'
      preLoaderRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/global/decks/$deckUuid/_deck': {
      id: '/_menu/global/decks/$deckUuid/_deck'
      path: '/global/decks/$deckUuid'
      fullPath: '/global/decks/$deckUuid'
      preLoaderRoute: typeof MenuGlobalDecksDeckUuidDeckRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/shared/collections/$token/_shared': {
      id: '/_menu/shared/collections/$token/_shared'
      path: '/shared/collections/$token'
      fullPath: '/shared/collections/$token'
      preLoaderRoute: typeof MenuSharedCollectionsTokenSharedRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/shared/decks/$token/_shared': {
      id: '/_menu/shared/decks/$token/_shared'
      path: '/shared/decks/$token'
      fullPath: '/shared/decks/$token'
      preLoaderRoute: typeof MenuSharedDecksTokenSharedRouteImport
      parentRoute: typeof MenuRoute
    }
    '/_menu/global/collections/$collectionUuid/_collection/': {
      id: '/_menu/global/collections/$collectionUuid/_collection/'
      path: '/'
      fullPath: '/global/collections/$collectionUuid/'
      preLoaderRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionIndexRouteImport
      parentRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/global/collections/$collectionUuid/_collection/cards': {
      id: '/_menu/global/collections/$collectionUuid/_collection/cards'
      path: '/cards'
      fullPath: '/global/collections/$collectionUuid/cards'
      preLoaderRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionCardsRouteImport
      parentRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/global/collections/$collectionUuid/_collection/statistics': {
      id: '/_menu/global/collections/$collectionUuid/_collection/statistics'
      path: '/statistics'
      fullPath: '/global/collections/$collectionUuid/statistics'
      preLoaderRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionStatisticsRouteImport
      parentRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionRoute
    }
    '/_menu/global/decks/$deckUuid/_deck/': {
      id: '/_menu/global/decks/$deckUuid/_deck/'
      path: '/'
      fullPath: '/global/decks/$deckUuid/'
      preLoaderRoute: typeof MenuGlobalDecksDeckUuidDeckIndexRouteImport
      parentRoute: typeof MenuGlobalDecksDeckUuidDeckRoute
    }
    '/_menu/global/decks/$deckUuid/_deck/cards': {
      id: '/_menu/global/decks/$deckUuid/_deck/cards'
      path: '/cards'
      fullPath: '/global/decks/$deckUuid/cards'
      preLoaderRoute: typeof MenuGlobalDecksDeckUuidDeckCardsRouteImport
      parentRoute: typeof MenuGlobalDecksDeckUuidDeckRoute
    }
    '/_menu/global/decks/$deckUuid/_deck/statistics': {
      id: '/_menu/global/decks/$deckUuid/_deck/statistics'
      path: '/statistics'
      fullPath: '/global/decks/$deckUuid/statistics'
      preLoaderRoute: typeof MenuGlobalDecksDeckUuidDeckStatisticsRouteImport
      parentRoute: typeof MenuGlobalDecksDeckUuidDeckRoute
    }
    '/_menu/shared/collections/$token/_shared/': {
      id: '/_menu/shared/collections/$token/_shared/'
      path: '/'
      fullPath: '/shared/collections/$token/'
      preLoaderRoute: typeof MenuSharedCollectionsTokenSharedIndexRouteImport
      parentRoute: typeof MenuSharedCollectionsTokenSharedRoute
    }
    '/_menu/shared/collections/$token/_shared/cards': {
      id: '/_menu/shared/collections/$token/_shared/cards'
      path: '/cards'
      fullPath: '/shared/collections/$token/cards'
      preLoaderRoute: typeof MenuSharedCollectionsTokenSharedCardsRouteImport
      parentRoute: typeof MenuSharedCollectionsTokenSharedRoute
    }
    '/_menu/shared/collections/$token/_shared/statistics': {
      id: '/_menu/shared/collections/$token/_shared/statistics'
      path: '/statistics'
      fullPath: '/shared/collections/$token/statistics'
      preLoaderRoute: typeof MenuSharedCollectionsTokenSharedStatisticsRouteImport
      parentRoute: typeof MenuSharedCollectionsTokenSharedRoute
    }
    '/_menu/shared/decks/$token/_shared/': {
      id: '/_menu/shared/decks/$token/_shared/'
      path: '/'
      fullPath: '/shared/decks/$token/'
      preLoaderRoute: typeof MenuSharedDecksTokenSharedIndexRouteImport
      parentRoute: typeof MenuSharedDecksTokenSharedRoute
    }
    '/_menu/shared/decks/$token/_shared/cards': {
      id: '/_menu/shared/decks/$token/_shared/cards'
      path: '/cards'
      fullPath: '/shared/decks/$token/cards'
      preLoaderRoute: typeof MenuSharedDecksTokenSharedCardsRouteImport
      parentRoute: typeof MenuSharedDecksTokenSharedRoute
    }
    '/_menu/shared/decks/$token/_shared/statistics': {
      id: '/_menu/shared/decks/$token/_shared/statistics'
      path: '/statistics'
      fullPath: '/shared/decks/$token/statistics'
      preLoaderRoute: typeof MenuSharedDecksTokenSharedStatisticsRouteImport
      parentRoute: typeof MenuSharedDecksTokenSharedRoute
    }
  }
}

interface CollectScanRouteChildren {
  CollectScanLiveRoute: typeof CollectScanLiveRoute
  CollectScanIndexRoute: typeof CollectScanIndexRoute
}

const CollectScanRouteChildren: CollectScanRouteChildren = {
  CollectScanLiveRoute: CollectScanLiveRoute,
  CollectScanIndexRoute: CollectScanIndexRoute,
}

const CollectScanRouteWithChildren = CollectScanRoute._addFileChildren(
  CollectScanRouteChildren,
)

interface CollectRouteChildren {
  CollectListeRoute: typeof CollectListeRoute
  CollectScanRoute: typeof CollectScanRouteWithChildren
}

const CollectRouteChildren: CollectRouteChildren = {
  CollectListeRoute: CollectListeRoute,
  CollectScanRoute: CollectScanRouteWithChildren,
}

const CollectRouteWithChildren =
  CollectRoute._addFileChildren(CollectRouteChildren)

interface MenuAuthRouteChildren {
  MenuAuthLoginRoute: typeof MenuAuthLoginRoute
  MenuAuthRegisterRoute: typeof MenuAuthRegisterRoute
  MenuAuthSignupRoute: typeof MenuAuthSignupRoute
}

const MenuAuthRouteChildren: MenuAuthRouteChildren = {
  MenuAuthLoginRoute: MenuAuthLoginRoute,
  MenuAuthRegisterRoute: MenuAuthRegisterRoute,
  MenuAuthSignupRoute: MenuAuthSignupRoute,
}

const MenuAuthRouteWithChildren = MenuAuthRoute._addFileChildren(
  MenuAuthRouteChildren,
)

interface MenuGameUtilsRouteChildren {
  MenuGameUtilsLifeTrackerRoute: typeof MenuGameUtilsLifeTrackerRoute
  MenuGameUtilsProxyPrinterRoute: typeof MenuGameUtilsProxyPrinterRoute
  MenuGameUtilsIndexRoute: typeof MenuGameUtilsIndexRoute
}

const MenuGameUtilsRouteChildren: MenuGameUtilsRouteChildren = {
  MenuGameUtilsLifeTrackerRoute: MenuGameUtilsLifeTrackerRoute,
  MenuGameUtilsProxyPrinterRoute: MenuGameUtilsProxyPrinterRoute,
  MenuGameUtilsIndexRoute: MenuGameUtilsIndexRoute,
}

const MenuGameUtilsRouteWithChildren = MenuGameUtilsRoute._addFileChildren(
  MenuGameUtilsRouteChildren,
)

interface MenuProfileProfileRouteChildren {
  MenuProfileProfileSecurityRoute: typeof MenuProfileProfileSecurityRoute
  MenuProfileProfileSettingsRoute: typeof MenuProfileProfileSettingsRoute
  MenuProfileProfileIndexRoute: typeof MenuProfileProfileIndexRoute
}

const MenuProfileProfileRouteChildren: MenuProfileProfileRouteChildren = {
  MenuProfileProfileSecurityRoute: MenuProfileProfileSecurityRoute,
  MenuProfileProfileSettingsRoute: MenuProfileProfileSettingsRoute,
  MenuProfileProfileIndexRoute: MenuProfileProfileIndexRoute,
}

const MenuProfileProfileRouteWithChildren =
  MenuProfileProfileRoute._addFileChildren(MenuProfileProfileRouteChildren)

interface MenuCollectionsCollectionUuidCollectionRouteChildren {
  MenuCollectionsCollectionUuidCollectionCardsRoute: typeof MenuCollectionsCollectionUuidCollectionCardsRoute
  MenuCollectionsCollectionUuidCollectionOnLoanRoute: typeof MenuCollectionsCollectionUuidCollectionOnLoanRoute
  MenuCollectionsCollectionUuidCollectionStatisticsRoute: typeof MenuCollectionsCollectionUuidCollectionStatisticsRoute
  MenuCollectionsCollectionUuidCollectionIndexRoute: typeof MenuCollectionsCollectionUuidCollectionIndexRoute
}

const MenuCollectionsCollectionUuidCollectionRouteChildren: MenuCollectionsCollectionUuidCollectionRouteChildren =
  {
    MenuCollectionsCollectionUuidCollectionCardsRoute:
      MenuCollectionsCollectionUuidCollectionCardsRoute,
    MenuCollectionsCollectionUuidCollectionOnLoanRoute:
      MenuCollectionsCollectionUuidCollectionOnLoanRoute,
    MenuCollectionsCollectionUuidCollectionStatisticsRoute:
      MenuCollectionsCollectionUuidCollectionStatisticsRoute,
    MenuCollectionsCollectionUuidCollectionIndexRoute:
      MenuCollectionsCollectionUuidCollectionIndexRoute,
  }

const MenuCollectionsCollectionUuidCollectionRouteWithChildren =
  MenuCollectionsCollectionUuidCollectionRoute._addFileChildren(
    MenuCollectionsCollectionUuidCollectionRouteChildren,
  )

interface MenuDecksDeckUuidDeckRouteChildren {
  MenuDecksDeckUuidDeckAdvisorRoute: typeof MenuDecksDeckUuidDeckAdvisorRoute
  MenuDecksDeckUuidDeckCardsRoute: typeof MenuDecksDeckUuidDeckCardsRoute
  MenuDecksDeckUuidDeckSourcingRoute: typeof MenuDecksDeckUuidDeckSourcingRoute
  MenuDecksDeckUuidDeckStatisticsRoute: typeof MenuDecksDeckUuidDeckStatisticsRoute
  MenuDecksDeckUuidDeckIndexRoute: typeof MenuDecksDeckUuidDeckIndexRoute
}

const MenuDecksDeckUuidDeckRouteChildren: MenuDecksDeckUuidDeckRouteChildren = {
  MenuDecksDeckUuidDeckAdvisorRoute: MenuDecksDeckUuidDeckAdvisorRoute,
  MenuDecksDeckUuidDeckCardsRoute: MenuDecksDeckUuidDeckCardsRoute,
  MenuDecksDeckUuidDeckSourcingRoute: MenuDecksDeckUuidDeckSourcingRoute,
  MenuDecksDeckUuidDeckStatisticsRoute: MenuDecksDeckUuidDeckStatisticsRoute,
  MenuDecksDeckUuidDeckIndexRoute: MenuDecksDeckUuidDeckIndexRoute,
}

const MenuDecksDeckUuidDeckRouteWithChildren =
  MenuDecksDeckUuidDeckRoute._addFileChildren(
    MenuDecksDeckUuidDeckRouteChildren,
  )

interface MenuGlobalCollectionsCollectionUuidCollectionRouteChildren {
  MenuGlobalCollectionsCollectionUuidCollectionCardsRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionCardsRoute
  MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute
  MenuGlobalCollectionsCollectionUuidCollectionIndexRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionIndexRoute
}

const MenuGlobalCollectionsCollectionUuidCollectionRouteChildren: MenuGlobalCollectionsCollectionUuidCollectionRouteChildren =
  {
    MenuGlobalCollectionsCollectionUuidCollectionCardsRoute:
      MenuGlobalCollectionsCollectionUuidCollectionCardsRoute,
    MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute:
      MenuGlobalCollectionsCollectionUuidCollectionStatisticsRoute,
    MenuGlobalCollectionsCollectionUuidCollectionIndexRoute:
      MenuGlobalCollectionsCollectionUuidCollectionIndexRoute,
  }

const MenuGlobalCollectionsCollectionUuidCollectionRouteWithChildren =
  MenuGlobalCollectionsCollectionUuidCollectionRoute._addFileChildren(
    MenuGlobalCollectionsCollectionUuidCollectionRouteChildren,
  )

interface MenuGlobalDecksDeckUuidDeckRouteChildren {
  MenuGlobalDecksDeckUuidDeckCardsRoute: typeof MenuGlobalDecksDeckUuidDeckCardsRoute
  MenuGlobalDecksDeckUuidDeckStatisticsRoute: typeof MenuGlobalDecksDeckUuidDeckStatisticsRoute
  MenuGlobalDecksDeckUuidDeckIndexRoute: typeof MenuGlobalDecksDeckUuidDeckIndexRoute
}

const MenuGlobalDecksDeckUuidDeckRouteChildren: MenuGlobalDecksDeckUuidDeckRouteChildren =
  {
    MenuGlobalDecksDeckUuidDeckCardsRoute:
      MenuGlobalDecksDeckUuidDeckCardsRoute,
    MenuGlobalDecksDeckUuidDeckStatisticsRoute:
      MenuGlobalDecksDeckUuidDeckStatisticsRoute,
    MenuGlobalDecksDeckUuidDeckIndexRoute:
      MenuGlobalDecksDeckUuidDeckIndexRoute,
  }

const MenuGlobalDecksDeckUuidDeckRouteWithChildren =
  MenuGlobalDecksDeckUuidDeckRoute._addFileChildren(
    MenuGlobalDecksDeckUuidDeckRouteChildren,
  )

interface MenuSharedCollectionsTokenSharedRouteChildren {
  MenuSharedCollectionsTokenSharedCardsRoute: typeof MenuSharedCollectionsTokenSharedCardsRoute
  MenuSharedCollectionsTokenSharedStatisticsRoute: typeof MenuSharedCollectionsTokenSharedStatisticsRoute
  MenuSharedCollectionsTokenSharedIndexRoute: typeof MenuSharedCollectionsTokenSharedIndexRoute
}

const MenuSharedCollectionsTokenSharedRouteChildren: MenuSharedCollectionsTokenSharedRouteChildren =
  {
    MenuSharedCollectionsTokenSharedCardsRoute:
      MenuSharedCollectionsTokenSharedCardsRoute,
    MenuSharedCollectionsTokenSharedStatisticsRoute:
      MenuSharedCollectionsTokenSharedStatisticsRoute,
    MenuSharedCollectionsTokenSharedIndexRoute:
      MenuSharedCollectionsTokenSharedIndexRoute,
  }

const MenuSharedCollectionsTokenSharedRouteWithChildren =
  MenuSharedCollectionsTokenSharedRoute._addFileChildren(
    MenuSharedCollectionsTokenSharedRouteChildren,
  )

interface MenuSharedDecksTokenSharedRouteChildren {
  MenuSharedDecksTokenSharedCardsRoute: typeof MenuSharedDecksTokenSharedCardsRoute
  MenuSharedDecksTokenSharedStatisticsRoute: typeof MenuSharedDecksTokenSharedStatisticsRoute
  MenuSharedDecksTokenSharedIndexRoute: typeof MenuSharedDecksTokenSharedIndexRoute
}

const MenuSharedDecksTokenSharedRouteChildren: MenuSharedDecksTokenSharedRouteChildren =
  {
    MenuSharedDecksTokenSharedCardsRoute: MenuSharedDecksTokenSharedCardsRoute,
    MenuSharedDecksTokenSharedStatisticsRoute:
      MenuSharedDecksTokenSharedStatisticsRoute,
    MenuSharedDecksTokenSharedIndexRoute: MenuSharedDecksTokenSharedIndexRoute,
  }

const MenuSharedDecksTokenSharedRouteWithChildren =
  MenuSharedDecksTokenSharedRoute._addFileChildren(
    MenuSharedDecksTokenSharedRouteChildren,
  )

interface MenuRouteChildren {
  MenuAuthRoute: typeof MenuAuthRouteWithChildren
  MenuGameUtilsRoute: typeof MenuGameUtilsRouteWithChildren
  MenuHomeRoute: typeof MenuHomeRoute
  MenuLegalRoute: typeof MenuLegalRoute
  MenuPrivacyRoute: typeof MenuPrivacyRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenuProfileProfileRoute: typeof MenuProfileProfileRouteWithChildren
  MenuWatchListsWatchListUuidRoute: typeof MenuWatchListsWatchListUuidRoute
  MenuCollectionsIndexRoute: typeof MenuCollectionsIndexRoute
  MenuDecksIndexRoute: typeof MenuDecksIndexRoute
  MenuWatchListsIndexRoute: typeof MenuWatchListsIndexRoute
  MenuCollectionsCollectionUuidCollectionRoute: typeof MenuCollectionsCollectionUuidCollectionRouteWithChildren
  MenuDecksDeckUuidDeckRoute: typeof MenuDecksDeckUuidDeckRouteWithChildren
  MenuGlobalProfilesUsernameRoute: typeof MenuGlobalProfilesUsernameRoute
  MenuGlobalDecksIndexRoute: typeof MenuGlobalDecksIndexRoute
  MenuGlobalCollectionsCollectionUuidCollectionRoute: typeof MenuGlobalCollectionsCollectionUuidCollectionRouteWithChildren
  MenuGlobalDecksDeckUuidDeckRoute: typeof MenuGlobalDecksDeckUuidDeckRouteWithChildren
  MenuSharedCollectionsTokenSharedRoute: typeof MenuSharedCollectionsTokenSharedRouteWithChildren
  MenuSharedDecksTokenSharedRoute: typeof MenuSharedDecksTokenSharedRouteWithChildren
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuAuthRoute: MenuAuthRouteWithChildren,
  MenuGameUtilsRoute: MenuGameUtilsRouteWithChildren,
  MenuHomeRoute: MenuHomeRoute,
  MenuLegalRoute: MenuLegalRoute,
  MenuPrivacyRoute: MenuPrivacyRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenuProfileProfileRoute: MenuProfileProfileRouteWithChildren,
  MenuWatchListsWatchListUuidRoute: MenuWatchListsWatchListUuidRoute,
  MenuCollectionsIndexRoute: MenuCollectionsIndexRoute,
  MenuDecksIndexRoute: MenuDecksIndexRoute,
  MenuWatchListsIndexRoute: MenuWatchListsIndexRoute,
  MenuCollectionsCollectionUuidCollectionRoute:
    MenuCollectionsCollectionUuidCollectionRouteWithChildren,
  MenuDecksDeckUuidDeckRoute: MenuDecksDeckUuidDeckRouteWithChildren,
  MenuGlobalProfilesUsernameRoute: MenuGlobalProfilesUsernameRoute,
  MenuGlobalDecksIndexRoute: MenuGlobalDecksIndexRoute,
  MenuGlobalCollectionsCollectionUuidCollectionRoute:
    MenuGlobalCollectionsCollectionUuidCollectionRouteWithChildren,
  MenuGlobalDecksDeckUuidDeckRoute:
    MenuGlobalDecksDeckUuidDeckRouteWithChildren,
  MenuSharedCollectionsTokenSharedRoute:
    MenuSharedCollectionsTokenSharedRouteWithChildren,
  MenuSharedDecksTokenSharedRoute: MenuSharedDecksTokenSharedRouteWithChildren,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CollectRoute: CollectRouteWithChildren,
  MenuRoute: MenuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
