/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as SammlungRouteImport } from './routes/sammlung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const SammlungRoute = SammlungRouteImport.update({
  id: '/sammlung',
  path: '/sammlung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks': typeof DecksRoute
  '/sammlung': typeof SammlungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks': typeof DecksRoute
  '/sammlung': typeof SammlungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks': typeof DecksRoute
  '/sammlung': typeof SammlungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decks' | '/sammlung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decks' | '/sammlung'
  id: '__root__' | '/' | '/decks' | '/sammlung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksRoute: typeof DecksRoute
  SammlungRoute: typeof SammlungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sammlung': {
      id: '/sammlung'
      path: '/sammlung'
      fullPath: '/sammlung'
      preLoaderRoute: typeof SammlungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksRoute: DecksRoute,
  SammlungRoute: SammlungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
