//! Raw protobuf definitions generated by `build.rs`

/// Raw protobuf definitions for `proto/mail/v1/mail.proto`
#[allow(missing_docs)]
pub mod mail_v1 {
    include!(concat!(env!("OUT_DIR"), "/mail.v1.rs"));
}
