[package]
edition = "2024"
name = "mailcow"
license = "MPL-2.0"
description = "Mailcow client SDK"
authors = ["Niklas Pfister <git@omikron.dev>"]

[dependencies]
# Errors
thiserror = { workspace = true }
# HTTP client
reqwest = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Tracing
tracing = { workspace = true }
